import { FoodItem } from '../types/nutrition';

export const BUILTIN_FOOD_DATABASE: FoodItem[] = [
  // --- STAPLES & KARBOHIDRAT ---
  {
    id: 'food_nasi_putih',
    name: 'Nasi Putih (White Rice)',
    indonesianName: 'Nasi Putih',
    category: 'Staples',
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    defaultServingText: '1 Piring Sedang (200g)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_nasi_merah',
    name: 'Nasi Merah (Brown Rice)',
    indonesianName: 'Nasi Merah',
    category: 'Staples',
    calories: 111,
    protein: 2.6,
    carbs: 23.0,
    fat: 0.9,
    fiber: 1.8,
    defaultServingText: '1 Piring Sedang (200g)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_nasi_goreng',
    name: 'Nasi Goreng Polos',
    indonesianName: 'Nasi Goreng',
    category: 'Staples',
    calories: 168,
    protein: 4.5,
    carbs: 24.0,
    fat: 6.2,
    defaultServingText: '1 Porsi (250g)',
    defaultServingGrams: 250,
  },
  {
    id: 'food_mie_instan',
    name: 'Mie Instan Kuah / Goreng (Matang)',
    indonesianName: 'Mie Instan',
    category: 'Staples',
    calories: 215,
    protein: 4.5,
    carbs: 28.5,
    fat: 9.2,
    defaultServingText: '1 Bungkus / Mangkok (150g matang)',
    defaultServingGrams: 150,
  },
  {
    id: 'food_kentang_rebus',
    name: 'Kentang Rebus / Kukus',
    indonesianName: 'Kentang Rebus',
    category: 'Staples',
    calories: 87,
    protein: 1.9,
    carbs: 20.1,
    fat: 0.1,
    fiber: 1.8,
    defaultServingText: '1 Buah Sedang (150g)',
    defaultServingGrams: 150,
  },
  {
    id: 'food_ubi_jalar',
    name: 'Ubi Jalar Rebus / Panggang',
    indonesianName: 'Ubi Jalar Rebus',
    category: 'Staples',
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3.0,
    defaultServingText: '1 Buah Sedang (130g)',
    defaultServingGrams: 130,
  },
  {
    id: 'food_oatmeal',
    name: 'Oatmeal (Rolled Oats Kering)',
    indonesianName: 'Oatmeal',
    category: 'Staples',
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    fiber: 10.6,
    defaultServingText: '1 Porsi Kering (40g)',
    defaultServingGrams: 40,
  },
  {
    id: 'food_roti_gandum',
    name: 'Roti Gandum (Whole Wheat Bread)',
    indonesianName: 'Roti Gandum',
    category: 'Staples',
    calories: 247,
    protein: 13.0,
    carbs: 41.0,
    fat: 3.4,
    fiber: 7.0,
    defaultServingText: '1 Lembar (40g)',
    defaultServingGrams: 40,
  },
  {
    id: 'food_roti_tawar',
    name: 'Roti Tawar Putih',
    indonesianName: 'Roti Tawar',
    category: 'Staples',
    calories: 265,
    protein: 9.0,
    carbs: 49.0,
    fat: 3.2,
    fiber: 2.7,
    defaultServingText: '1 Lembar (35g)',
    defaultServingGrams: 35,
  },
  {
    id: 'food_lontong',
    name: 'Lontong / Ketupat',
    indonesianName: 'Lontong',
    category: 'Staples',
    calories: 130,
    protein: 2.5,
    carbs: 28.0,
    fat: 0.2,
    defaultServingText: '1 Buah Sedang (150g)',
    defaultServingGrams: 150,
  },

  // --- PROTEINS (LAUK PAUK & DAGING) ---
  {
    id: 'food_dada_ayam_rebus',
    name: 'Dada Ayam Rebus / Kukus (Skinless)',
    indonesianName: 'Dada Ayam Rebus',
    category: 'Proteins',
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    defaultServingText: '1 Porsi Fillet (120g)',
    defaultServingGrams: 120,
  },
  {
    id: 'food_dada_ayam_panggang',
    name: 'Dada Ayam Panggang (Grilled Chicken)',
    indonesianName: 'Dada Ayam Panggang',
    category: 'Proteins',
    calories: 175,
    protein: 31.5,
    carbs: 0.5,
    fat: 4.8,
    defaultServingText: '1 Potong Sedang (120g)',
    defaultServingGrams: 120,
  },
  {
    id: 'food_ayam_goreng',
    name: 'Paha Ayam Goreng (Fried Chicken)',
    indonesianName: 'Ayam Goreng',
    category: 'Proteins',
    calories: 245,
    protein: 22.0,
    carbs: 3.0,
    fat: 16.0,
    defaultServingText: '1 Potong Paha (100g)',
    defaultServingGrams: 100,
  },
  {
    id: 'food_telur_rebus',
    name: 'Telur Ayam Rebus (Boiled Egg)',
    indonesianName: 'Telur Rebus',
    category: 'Proteins',
    calories: 155,
    protein: 13.0,
    carbs: 1.1,
    fat: 11.0,
    defaultServingText: '1 Butir (55g)',
    defaultServingGrams: 55,
  },
  {
    id: 'food_putih_telur',
    name: 'Putih Telur Rebus (Egg White)',
    indonesianName: 'Putih Telur Rebus',
    category: 'Proteins',
    calories: 52,
    protein: 11.0,
    carbs: 0.7,
    fat: 0.2,
    defaultServingText: '1 Butir Putih Telur (33g)',
    defaultServingGrams: 33,
  },
  {
    id: 'food_telur_dadar',
    name: 'Telur Dadar / Ceplok Goreng',
    indonesianName: 'Telur Dadar',
    category: 'Proteins',
    calories: 196,
    protein: 13.6,
    carbs: 1.2,
    fat: 15.3,
    defaultServingText: '1 Butir Dadar (60g)',
    defaultServingGrams: 60,
  },
  {
    id: 'food_tempe_goreng',
    name: 'Tempe Goreng Tepung / Polos',
    indonesianName: 'Tempe Goreng',
    category: 'Proteins',
    calories: 220,
    protein: 18.0,
    carbs: 10.0,
    fat: 12.0,
    defaultServingText: '1 Potong Sedang (50g)',
    defaultServingGrams: 50,
  },
  {
    id: 'food_tempe_bacem',
    name: 'Tempe Bacem / Kukus',
    indonesianName: 'Tempe Kukus / Bacem',
    category: 'Proteins',
    calories: 192,
    protein: 19.0,
    carbs: 12.0,
    fat: 7.7,
    defaultServingText: '1 Potong Sedang (50g)',
    defaultServingGrams: 50,
  },
  {
    id: 'food_tahu_goreng',
    name: 'Tahu Goreng',
    indonesianName: 'Tahu Goreng',
    category: 'Proteins',
    calories: 115,
    protein: 10.0,
    carbs: 4.0,
    fat: 7.0,
    defaultServingText: '1 Potong (50g)',
    defaultServingGrams: 50,
  },
  {
    id: 'food_tahu_putih',
    name: 'Tahu Putih Rebus / Kukus',
    indonesianName: 'Tahu Putih Kukus',
    category: 'Proteins',
    calories: 76,
    protein: 8.1,
    carbs: 1.9,
    fat: 4.8,
    defaultServingText: '1 Potong (80g)',
    defaultServingGrams: 80,
  },
  {
    id: 'food_daging_sapi_lean',
    name: 'Daging Sapi Tanpa Lemak (Lean Beef)',
    indonesianName: 'Daging Sapi Tanpa Lemak',
    category: 'Proteins',
    calories: 217,
    protein: 26.1,
    carbs: 0.0,
    fat: 11.8,
    defaultServingText: '1 Potong (100g)',
    defaultServingGrams: 100,
  },
  {
    id: 'food_rendang',
    name: 'Rendang Daging Sapi',
    indonesianName: 'Rendang Sapi',
    category: 'Proteins',
    calories: 195,
    protein: 19.5,
    carbs: 5.0,
    fat: 11.0,
    defaultServingText: '1 Potong Sedang (70g)',
    defaultServingGrams: 70,
  },
  {
    id: 'food_ikan_salmon',
    name: 'Ikan Salmon Panggang',
    indonesianName: 'Ikan Salmon',
    category: 'Proteins',
    calories: 206,
    protein: 22.0,
    carbs: 0.0,
    fat: 12.3,
    defaultServingText: '1 Fillet (125g)',
    defaultServingGrams: 125,
  },
  {
    id: 'food_ikan_tongkol',
    name: 'Ikan Tongkol / Cakalang Balado',
    indonesianName: 'Ikan Tongkol Balado',
    category: 'Proteins',
    calories: 145,
    protein: 23.0,
    carbs: 3.5,
    fat: 4.2,
    defaultServingText: '1 Potong (100g)',
    defaultServingGrams: 100,
  },
  {
    id: 'food_ikan_lele',
    name: 'Ikan Lele Goreng',
    indonesianName: 'Ikan Lele Goreng',
    category: 'Proteins',
    calories: 240,
    protein: 18.0,
    carbs: 6.0,
    fat: 16.0,
    defaultServingText: '1 Ekor Sedang (120g)',
    defaultServingGrams: 120,
  },
  {
    id: 'food_udang_rebus',
    name: 'Udang Rebus / Tumis',
    indonesianName: 'Udang Rebus',
    category: 'Proteins',
    calories: 99,
    protein: 24.0,
    carbs: 0.2,
    fat: 0.3,
    defaultServingText: '1 Porsi (100g)',
    defaultServingGrams: 100,
  },
  {
    id: 'food_whey_protein',
    name: 'Whey Protein Isolate (Powder)',
    indonesianName: 'Whey Protein',
    category: 'Proteins',
    calories: 380,
    protein: 80.0,
    carbs: 5.0,
    fat: 3.0,
    defaultServingText: '1 Scoop (30g)',
    defaultServingGrams: 30,
  },

  // --- VEGETABLES & SOUPS ---
  {
    id: 'food_sayur_sop',
    name: 'Sayur Sop Bening Ayam / Sayur',
    indonesianName: 'Sayur Sop',
    category: 'Vegetables',
    calories: 45,
    protein: 3.5,
    carbs: 5.0,
    fat: 1.2,
    defaultServingText: '1 Mangkok (250g)',
    defaultServingGrams: 250,
  },
  {
    id: 'food_sayur_asem',
    name: 'Sayur Asem',
    indonesianName: 'Sayur Asem',
    category: 'Vegetables',
    calories: 35,
    protein: 1.5,
    carbs: 6.0,
    fat: 0.8,
    defaultServingText: '1 Mangkok (250g)',
    defaultServingGrams: 250,
  },
  {
    id: 'food_tumis_kangkung',
    name: 'Tumis Kangkung Terasi',
    indonesianName: 'Tumis Kangkung',
    category: 'Vegetables',
    calories: 68,
    protein: 2.6,
    carbs: 4.2,
    fat: 4.8,
    defaultServingText: '1 Porsi Piring (150g)',
    defaultServingGrams: 150,
  },
  {
    id: 'food_brokoli',
    name: 'Brokoli Kukus / Rebus',
    indonesianName: 'Brokoli Rebus',
    category: 'Vegetables',
    calories: 35,
    protein: 2.8,
    carbs: 7.2,
    fat: 0.4,
    fiber: 2.6,
    defaultServingText: '1 Mangkok (100g)',
    defaultServingGrams: 100,
  },
  {
    id: 'food_bayam_bening',
    name: 'Sayur Bening Bayam & Jagung',
    indonesianName: 'Sayur Bening Bayam',
    category: 'Vegetables',
    calories: 30,
    protein: 2.2,
    carbs: 4.8,
    fat: 0.4,
    defaultServingText: '1 Mangkok (200g)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_gado_gado',
    name: 'Gado-Gado dengan Bumbu Kacang',
    indonesianName: 'Gado-Gado',
    category: 'Vegetables',
    calories: 135,
    protein: 6.0,
    carbs: 14.0,
    fat: 7.0,
    defaultServingText: '1 Porsi Lengkap (250g)',
    defaultServingGrams: 250,
  },

  // --- FRUITS ---
  {
    id: 'food_pisang',
    name: 'Pisang Cavendish / Ambon',
    indonesianName: 'Pisang',
    category: 'Fruits',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    defaultServingText: '1 Buah Sedang (118g)',
    defaultServingGrams: 118,
  },
  {
    id: 'food_apel',
    name: 'Apel Segar (Fuji / Malang)',
    indonesianName: 'Apel Segar',
    category: 'Fruits',
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    defaultServingText: '1 Buah Sedang (150g)',
    defaultServingGrams: 150,
  },
  {
    id: 'food_alpukat',
    name: 'Alpukat Segar (Avocado)',
    indonesianName: 'Alpukat',
    category: 'Fruits',
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    defaultServingText: 'Setengah Buah (100g)',
    defaultServingGrams: 100,
  },
  {
    id: 'food_semangka',
    name: 'Semangka Potong Segar',
    indonesianName: 'Semangka',
    category: 'Fruits',
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    defaultServingText: '1 Irisan Sedang (150g)',
    defaultServingGrams: 150,
  },
  {
    id: 'food_pepaya',
    name: 'Pepaya Matang Potong',
    indonesianName: 'Pepaya',
    category: 'Fruits',
    calories: 43,
    protein: 0.5,
    carbs: 10.8,
    fat: 0.3,
    fiber: 1.7,
    defaultServingText: '1 Mangkok Potong (150g)',
    defaultServingGrams: 150,
  },

  // --- DAIRY & DRINKS ---
  {
    id: 'food_kopi_hitam',
    name: 'Kopi Hitam / Americano (Tanpa Gula)',
    indonesianName: 'Kopi Hitam',
    category: 'Dairy & Drinks',
    calories: 2,
    protein: 0.3,
    carbs: 0.2,
    fat: 0.0,
    defaultServingText: '1 Cangkir (240ml)',
    defaultServingGrams: 240,
  },
  {
    id: 'food_kopi_susu',
    name: 'Kopi Susu Gula Aren',
    indonesianName: 'Kopi Susu Gula Aren',
    category: 'Dairy & Drinks',
    calories: 72,
    protein: 1.4,
    carbs: 11.2,
    fat: 2.4,
    defaultServingText: '1 Cup Regular (250ml)',
    defaultServingGrams: 250,
  },
  {
    id: 'food_susu_uht_full',
    name: 'Susu UHT Full Cream',
    indonesianName: 'Susu Full Cream',
    category: 'Dairy & Drinks',
    calories: 65,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.5,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_susu_low_fat',
    name: 'Susu Low Fat / Rendah Lemak',
    indonesianName: 'Susu Low Fat',
    category: 'Dairy & Drinks',
    calories: 42,
    protein: 3.4,
    carbs: 5.0,
    fat: 1.0,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_yogurt_greek',
    name: 'Greek Yogurt Plain',
    indonesianName: 'Greek Yogurt Plain',
    category: 'Dairy & Drinks',
    calories: 59,
    protein: 10.0,
    carbs: 3.6,
    fat: 0.4,
    defaultServingText: '1 Cup (120g)',
    defaultServingGrams: 120,
  },

  // --- SNACKS & FAST FOOD ---
  {
    id: 'food_bakso_sapi',
    name: 'Bakso Sapi Kuah Lengkap',
    indonesianName: 'Bakso Sapi Kuah',
    category: 'Snacks',
    calories: 120,
    protein: 8.0,
    carbs: 10.0,
    fat: 5.0,
    defaultServingText: '1 Porsi Mangkok (300g)',
    defaultServingGrams: 300,
  },
  {
    id: 'food_sate_ayam',
    name: 'Sate Ayam Bumbu Kacang',
    indonesianName: 'Sate Ayam',
    category: 'Snacks',
    calories: 185,
    protein: 16.0,
    carbs: 8.0,
    fat: 10.0,
    defaultServingText: '5 Tusuk (150g)',
    defaultServingGrams: 150,
  },
  {
    id: 'food_gorengan_bakwan',
    name: 'Gorengan Bakwan / Bala-Bala',
    indonesianName: 'Bakwan Goreng',
    category: 'Snacks',
    calories: 280,
    protein: 4.0,
    carbs: 35.0,
    fat: 14.0,
    defaultServingText: '1 Pcs (50g)',
    defaultServingGrams: 50,
  },
  {
    id: 'food_martabak_manis',
    name: 'Martabak Manis Coklat Keju',
    indonesianName: 'Martabak Manis',
    category: 'Snacks',
    calories: 290,
    protein: 5.5,
    carbs: 45.0,
    fat: 10.5,
    defaultServingText: '1 Potong Sedang (80g)',
    defaultServingGrams: 80,
  },
  {
    id: 'food_martabak_telur',
    name: 'Martabak Telur Daging',
    indonesianName: 'Martabak Telur',
    category: 'Snacks',
    calories: 240,
    protein: 10.0,
    carbs: 18.0,
    fat: 14.0,
    defaultServingText: '2 Potong (100g)',
    defaultServingGrams: 100,
  },

  // --- SNACKS KEMASAN INDONESIA (CHIPS, BISKUIT & KERIPIK) ---
  {
    id: 'snack_qtela_singkong_balado',
    name: 'Qtela Keripik Singkong Balado',
    indonesianName: 'Keripik Singkong Qtela Balado Pedas Manis',
    category: 'Snacks',
    calories: 490,
    protein: 2.8,
    carbs: 64.0,
    fat: 24.5,
    fiber: 3.5,
    defaultServingText: '1 Bungkus Kecil / Saji (30g)',
    defaultServingGrams: 30,
  },
  {
    id: 'snack_qtela_singkong_original',
    name: 'Qtela Keripik Singkong Original / Asin Gurih',
    indonesianName: 'Qtela Singkong Original',
    category: 'Snacks',
    calories: 500,
    protein: 2.5,
    carbs: 63.0,
    fat: 26.0,
    fiber: 3.2,
    defaultServingText: '1 Porsi Saji (30g)',
    defaultServingGrams: 30,
  },
  {
    id: 'snack_qtela_tempe_original',
    name: 'Qtela Keripik Tempe Original',
    indonesianName: 'Keripik Tempe Qtela Asin Gurih',
    category: 'Snacks',
    calories: 520,
    protein: 16.0,
    carbs: 48.0,
    fat: 28.0,
    fiber: 5.0,
    defaultServingText: '1 Bungkus Saji (30g)',
    defaultServingGrams: 30,
  },
  {
    id: 'snack_chitato_sapi_panggang',
    name: 'Chitato Beef Barbecue / Sapi Panggang',
    indonesianName: 'Keripik Kentang Chitato Sapi Panggang',
    category: 'Snacks',
    calories: 533,
    protein: 6.7,
    carbs: 53.3,
    fat: 33.3,
    fiber: 3.3,
    defaultServingText: '1 Bungkus Sedang (68g)',
    defaultServingGrams: 68,
  },
  {
    id: 'snack_chitato_ayam_bumbu',
    name: 'Chitato Ayam Bumbu (Spicy Chicken)',
    indonesianName: 'Chitato Ayam Bumbu Pedas',
    category: 'Snacks',
    calories: 530,
    protein: 6.5,
    carbs: 54.0,
    fat: 32.5,
    defaultServingText: '1 Bungkus Sedang (68g)',
    defaultServingGrams: 68,
  },
  {
    id: 'snack_chitato_lite_rumput_laut',
    name: 'Chitato Lite Seaweed / Rumput Laut (Ex-Lays)',
    indonesianName: 'Chitato Lite Rumput Laut Lays',
    category: 'Snacks',
    calories: 520,
    protein: 7.0,
    carbs: 56.0,
    fat: 30.0,
    fiber: 3.0,
    defaultServingText: '1 Bungkus (68g)',
    defaultServingGrams: 68,
  },
  {
    id: 'snack_kusuka_singkong_balado',
    name: 'Kusuka Keripik Singkong Balado',
    indonesianName: 'Kusuka Balado Pedas',
    category: 'Snacks',
    calories: 480,
    protein: 2.5,
    carbs: 65.0,
    fat: 23.0,
    fiber: 4.0,
    defaultServingText: '1 Bungkus (60g)',
    defaultServingGrams: 60,
  },
  {
    id: 'snack_kusuka_rumput_laut',
    name: 'Kusuka Keripik Singkong Rumput Laut',
    indonesianName: 'Kusuka Rumput Laut',
    category: 'Snacks',
    calories: 490,
    protein: 2.8,
    carbs: 64.0,
    fat: 24.0,
    defaultServingText: '1 Bungkus (60g)',
    defaultServingGrams: 60,
  },
  {
    id: 'snack_taro_net_rumput_laut',
    name: 'Taro Net Seaweed / Rumput Laut',
    indonesianName: 'Taro Net Rumput Laut',
    category: 'Snacks',
    calories: 460,
    protein: 6.0,
    carbs: 70.0,
    fat: 17.5,
    defaultServingText: '1 Bungkus (36g)',
    defaultServingGrams: 36,
  },
  {
    id: 'snack_chiki_balls_keju',
    name: 'Chiki Balls Keju (Cheese)',
    indonesianName: 'Chiki Balls Rasa Keju',
    category: 'Snacks',
    calories: 510,
    protein: 7.0,
    carbs: 58.0,
    fat: 27.5,
    defaultServingText: '1 Bungkus (55g)',
    defaultServingGrams: 55,
  },
  {
    id: 'snack_chiki_twist_jagung_bakar',
    name: 'Chiki Twist Jagung Bakar (Ex-Cheetos)',
    indonesianName: 'Chiki Twist Cheetos Jagung Bakar',
    category: 'Snacks',
    calories: 525,
    protein: 6.5,
    carbs: 60.0,
    fat: 28.5,
    defaultServingText: '1 Bungkus (40g)',
    defaultServingGrams: 40,
  },
  {
    id: 'snack_potabee_daging_bbq',
    name: 'Potabee Potato Chips Daging BBQ',
    indonesianName: 'Potabee Daging BBQ',
    category: 'Snacks',
    calories: 540,
    protein: 6.0,
    carbs: 54.0,
    fat: 33.0,
    defaultServingText: '1 Bungkus (68g)',
    defaultServingGrams: 68,
  },
  {
    id: 'snack_pringles_original',
    name: 'Pringles Potato Crisps Original',
    indonesianName: 'Pringles Original Asin',
    category: 'Snacks',
    calories: 528,
    protein: 4.2,
    carbs: 56.4,
    fat: 31.7,
    defaultServingText: '1 Tube Sedang (107g)',
    defaultServingGrams: 107,
  },
  {
    id: 'snack_pringles_sour_cream',
    name: 'Pringles Sour Cream & Onion',
    indonesianName: 'Pringles Sour Cream Onion',
    category: 'Snacks',
    calories: 525,
    protein: 4.5,
    carbs: 55.0,
    fat: 32.0,
    defaultServingText: '1 Tube Sedang (107g)',
    defaultServingGrams: 107,
  },
  {
    id: 'snack_oreo_vanilla',
    name: 'Oreo Sandwich Cookies Vanilla Cream',
    indonesianName: 'Biskuit Oreo Krim Vanila',
    category: 'Snacks',
    calories: 480,
    protein: 4.8,
    carbs: 70.0,
    fat: 20.0,
    defaultServingText: '3 Keping Oreo (28.5g)',
    defaultServingGrams: 29,
  },
  {
    id: 'snack_roma_kelapa',
    name: 'Biskuit Roma Kelapa',
    indonesianName: 'Biskuit Roma Kelapa',
    category: 'Snacks',
    calories: 466,
    protein: 6.6,
    carbs: 73.3,
    fat: 16.6,
    defaultServingText: '3 Keping (27g)',
    defaultServingGrams: 27,
  },
  {
    id: 'snack_roma_malkist_abon',
    name: 'Roma Malkist Crackers Abon Sapi',
    indonesianName: 'Roma Malkist Abon',
    category: 'Snacks',
    calories: 460,
    protein: 9.0,
    carbs: 68.0,
    fat: 16.5,
    defaultServingText: '1 Bungkus Saji (27g)',
    defaultServingGrams: 27,
  },
  {
    id: 'snack_roma_malkist_cokelat',
    name: 'Roma Malkist Cokelat',
    indonesianName: 'Roma Malkist Cokelat',
    category: 'Snacks',
    calories: 475,
    protein: 6.0,
    carbs: 70.0,
    fat: 18.5,
    defaultServingText: '2 Keping (24g)',
    defaultServingGrams: 24,
  },
  {
    id: 'snack_roma_slai_olai',
    name: 'Roma Slai O Lai Strawberry',
    indonesianName: 'Slai O Lai Selai Stroberi',
    category: 'Snacks',
    calories: 450,
    protein: 5.0,
    carbs: 74.0,
    fat: 15.0,
    defaultServingText: '1 Bungkus Kecil (32g)',
    defaultServingGrams: 32,
  },
  {
    id: 'snack_beng_beng',
    name: 'Beng-Beng Wafer Coklat Karamel Crispy',
    indonesianName: 'Beng Beng Wafer Coklat',
    category: 'Snacks',
    calories: 500,
    protein: 5.0,
    carbs: 64.0,
    fat: 25.0,
    defaultServingText: '1 Bar (25g)',
    defaultServingGrams: 25,
  },
  {
    id: 'snack_silverqueen_cashew',
    name: 'SilverQueen Milk Chocolate Cashew (Kacang Mede)',
    indonesianName: 'Coklat Silverqueen Mede',
    category: 'Snacks',
    calories: 550,
    protein: 9.5,
    carbs: 52.0,
    fat: 34.0,
    defaultServingText: '1 Bar Sedang (58g)',
    defaultServingGrams: 58,
  },
  {
    id: 'snack_kitkat_chocolate',
    name: 'KitKat 4 Finger Milk Chocolate',
    indonesianName: 'Kit Kat Wafer Coklat',
    category: 'Snacks',
    calories: 518,
    protein: 6.5,
    carbs: 64.5,
    fat: 26.8,
    defaultServingText: '1 Pack 4 Bar (35g)',
    defaultServingGrams: 35,
  },
  {
    id: 'snack_tango_wafer_cokelat',
    name: 'Wafer Tango Cokelat',
    indonesianName: 'Wafer Tango Cokelat',
    category: 'Snacks',
    calories: 490,
    protein: 5.0,
    carbs: 66.0,
    fat: 22.0,
    defaultServingText: '1 Bungkus Saji (47g)',
    defaultServingGrams: 47,
  },
  {
    id: 'snack_gery_saluut_malkist_keju',
    name: 'Gery Saluut Malkist Keju',
    indonesianName: 'Gery Saluut Malkist Keju',
    category: 'Snacks',
    calories: 480,
    protein: 7.0,
    carbs: 68.0,
    fat: 20.0,
    defaultServingText: '2 Keping (22g)',
    defaultServingGrams: 22,
  },
  {
    id: 'snack_pocky_chocolate',
    name: 'Glico Pocky Chocolate Biscuit Sticks',
    indonesianName: 'Pocky Coklat',
    category: 'Snacks',
    calories: 490,
    protein: 7.5,
    carbs: 68.0,
    fat: 20.5,
    defaultServingText: '1 Kotak (47g)',
    defaultServingGrams: 47,
  },
  {
    id: 'snack_garuda_kacang_kulit',
    name: 'Kacang Kulit Garuda Asin Gurih',
    indonesianName: 'Kacang Kulit Garuda',
    category: 'Snacks',
    calories: 570,
    protein: 26.0,
    carbs: 18.0,
    fat: 45.0,
    fiber: 8.0,
    defaultServingText: '1 Genggam (30g kupas)',
    defaultServingGrams: 30,
  },
  {
    id: 'snack_garuda_kacang_atom',
    name: 'Kacang Atom Garuda',
    indonesianName: 'Kacang Atom Garuda',
    category: 'Snacks',
    calories: 520,
    protein: 11.0,
    carbs: 60.0,
    fat: 26.0,
    defaultServingText: '1 Bungkus (50g)',
    defaultServingGrams: 50,
  },
  {
    id: 'snack_sukro_original',
    name: 'Dua Kelinci Sukro Kacang Polong Berbalut',
    indonesianName: 'Kacang Sukro Original',
    category: 'Snacks',
    calories: 485,
    protein: 8.0,
    carbs: 65.0,
    fat: 21.0,
    defaultServingText: '1 Bungkus (40g)',
    defaultServingGrams: 40,
  },
  {
    id: 'snack_kerupuk_putih_kaleng',
    name: 'Kerupuk Putih Kaleng / Kerupuk Uyel Warung',
    indonesianName: 'Kerupuk Kaleng Putih Warung',
    category: 'Snacks',
    calories: 480,
    protein: 1.5,
    carbs: 72.0,
    fat: 21.0,
    defaultServingText: '1 Buah (15g)',
    defaultServingGrams: 15,
  },
  {
    id: 'snack_kerupuk_bawang',
    name: 'Kerupuk Bawang Warna Warni',
    indonesianName: 'Kerupuk Bawang',
    category: 'Snacks',
    calories: 460,
    protein: 2.0,
    carbs: 75.0,
    fat: 17.0,
    defaultServingText: '1 Porsi (20g)',
    defaultServingGrams: 20,
  },
  {
    id: 'snack_emping_melinjo',
    name: 'Emping Melinjo Goreng',
    indonesianName: 'Emping Melinjo',
    category: 'Snacks',
    calories: 500,
    protein: 8.0,
    carbs: 62.0,
    fat: 24.0,
    defaultServingText: '1 Porsi (25g)',
    defaultServingGrams: 25,
  },
  {
    id: 'snack_basreng_pedas',
    name: 'Basreng Pedas Daun Jeruk (Bakso Goreng Kering)',
    indonesianName: 'Basreng Pedas Kering Daun Jeruk',
    category: 'Snacks',
    calories: 490,
    protein: 12.0,
    carbs: 58.0,
    fat: 23.0,
    defaultServingText: '1 Porsi (50g)',
    defaultServingGrams: 50,
  },
  {
    id: 'snack_makaroni_pedas',
    name: 'Makaroni Goreng Pedas Gurih (Ngehe style)',
    indonesianName: 'Makaroni Pedas Kering',
    category: 'Snacks',
    calories: 465,
    protein: 8.0,
    carbs: 68.0,
    fat: 18.0,
    defaultServingText: '1 Bungkus (50g)',
    defaultServingGrams: 50,
  },
  {
    id: 'snack_cireng_rujak',
    name: 'Cireng Goreng Bumbu Rujak',
    indonesianName: 'Cireng Goreng Rujak',
    category: 'Snacks',
    calories: 310,
    protein: 1.5,
    carbs: 55.0,
    fat: 10.0,
    defaultServingText: '3 Pcs + Bumbu (90g)',
    defaultServingGrams: 90,
  },
  {
    id: 'snack_batagor_bumbu_kacang',
    name: 'Batagor Goreng Lengkap Bumbu Kacang',
    indonesianName: 'Batagor Goreng Kacang',
    category: 'Snacks',
    calories: 220,
    protein: 7.5,
    carbs: 22.0,
    fat: 11.5,
    defaultServingText: '1 Porsi (200g)',
    defaultServingGrams: 200,
  },
  {
    id: 'snack_siomay_ikan_bumbu_kacang',
    name: 'Siomay Ikan Bandung Kukus Bumbu Kacang',
    indonesianName: 'Siomay Bandung Kukus',
    category: 'Snacks',
    calories: 160,
    protein: 8.0,
    carbs: 18.0,
    fat: 6.5,
    defaultServingText: '1 Porsi 4 Buah (200g)',
    defaultServingGrams: 200,
  },
  {
    id: 'snack_risol_mayo',
    name: 'Risol Mayo Telur Smoke Beef Goreng',
    indonesianName: 'Risol Mayo Smoked Beef',
    category: 'Snacks',
    calories: 275,
    protein: 6.5,
    carbs: 26.0,
    fat: 16.0,
    defaultServingText: '1 Buah (80g)',
    defaultServingGrams: 80,
  },
  {
    id: 'snack_tahu_isi_goreng',
    name: 'Tahu Isi Sayur / Gehu Goreng Tepung',
    indonesianName: 'Tahu Isi Gorengan Gehu',
    category: 'Snacks',
    calories: 210,
    protein: 6.0,
    carbs: 20.0,
    fat: 12.0,
    defaultServingText: '1 Buah (60g)',
    defaultServingGrams: 60,
  },
  {
    id: 'snack_pisang_goreng',
    name: 'Pisang Goreng Tepung Crispy',
    indonesianName: 'Pisang Goreng Crispy',
    category: 'Snacks',
    calories: 250,
    protein: 2.2,
    carbs: 42.0,
    fat: 9.0,
    fiber: 2.0,
    defaultServingText: '1 Buah (70g)',
    defaultServingGrams: 70,
  },

  // --- MINUMAN KEMASAN POPULER (DAIRY & DRINKS) ---
  {
    id: 'drink_ultra_milk_full_cream',
    name: 'Ultra Milk UHT Full Cream Putih',
    indonesianName: 'Susu Ultra Milk Full Cream',
    category: 'Dairy & Drinks',
    calories: 60,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.2,
    defaultServingText: '1 Kotak (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'drink_ultra_milk_chocolate',
    name: 'Ultra Milk UHT Cokelat (Chocolate)',
    indonesianName: 'Susu Ultra Milk Coklat',
    category: 'Dairy & Drinks',
    calories: 80,
    protein: 3.0,
    carbs: 11.5,
    fat: 2.5,
    defaultServingText: '1 Kotak (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'drink_ultra_milk_low_fat',
    name: 'Ultra Milk Low Fat Hi-Cal Calcium',
    indonesianName: 'Ultra Milk Low Fat Rendah Lemak',
    category: 'Dairy & Drinks',
    calories: 45,
    protein: 3.5,
    carbs: 5.5,
    fat: 1.0,
    defaultServingText: '1 Kotak (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'drink_bear_brand',
    name: 'Susu Bear Brand Nestle (Susu Beruang)',
    indonesianName: 'Bear Brand Susu Beruang Steril',
    category: 'Dairy & Drinks',
    calories: 63,
    protein: 3.2,
    carbs: 4.7,
    fat: 3.7,
    defaultServingText: '1 Kaleng (189ml)',
    defaultServingGrams: 189,
  },
  {
    id: 'drink_pocari_sweat',
    name: 'Pocari Sweat Isotonic Drink',
    indonesianName: 'Pocari Sweat Minuman Isotonik',
    category: 'Dairy & Drinks',
    calories: 25,
    protein: 0.0,
    carbs: 6.2,
    fat: 0.0,
    defaultServingText: '1 Botol (350ml / 500ml)',
    defaultServingGrams: 350,
  },
  {
    id: 'drink_teh_botol_sosro',
    name: 'Teh Botol Sosro Original Kotak / Botol',
    indonesianName: 'Teh Botol Sosro Manis',
    category: 'Dairy & Drinks',
    calories: 32,
    protein: 0.0,
    carbs: 8.0,
    fat: 0.0,
    defaultServingText: '1 Kotak (250ml)',
    defaultServingGrams: 250,
  },
  {
    id: 'drink_teh_pucuk_harum',
    name: 'Teh Pucuk Harum Melati',
    indonesianName: 'Teh Pucuk Harum',
    category: 'Dairy & Drinks',
    calories: 30,
    protein: 0.0,
    carbs: 7.5,
    fat: 0.0,
    defaultServingText: '1 Botol (350ml)',
    defaultServingGrams: 350,
  },
  {
    id: 'drink_yakult',
    name: 'Yakult Minuman Probiotik Fermentasi',
    indonesianName: 'Yakult Probiotik',
    category: 'Dairy & Drinks',
    calories: 77,
    protein: 1.2,
    carbs: 17.5,
    fat: 0.1,
    defaultServingText: '1 Botol Kecil (65ml)',
    defaultServingGrams: 65,
  },
  {
    id: 'drink_coca_cola_original',
    name: 'Coca Cola Original Can / Botol',
    indonesianName: 'Coca Cola Soda Original',
    category: 'Dairy & Drinks',
    calories: 42,
    protein: 0.0,
    carbs: 10.6,
    fat: 0.0,
    defaultServingText: '1 Kaleng (330ml)',
    defaultServingGrams: 330,
  },
  {
    id: 'drink_coca_cola_zero',
    name: 'Coca Cola Zero Sugar / No Calorie',
    indonesianName: 'Coca Cola Zero Gula',
    category: 'Dairy & Drinks',
    calories: 0,
    protein: 0.0,
    carbs: 0.0,
    fat: 0.0,
    defaultServingText: '1 Kaleng (330ml)',
    defaultServingGrams: 330,
  },
  {
    id: 'drink_kopi_kenangan_mantan',
    name: 'Kopi Kenangan Mantan (Gula Aren)',
    indonesianName: 'Kopi Susu Gula Aren Kenangan',
    category: 'Dairy & Drinks',
    calories: 95,
    protein: 2.0,
    carbs: 14.5,
    fat: 3.5,
    defaultServingText: '1 Cup Reguler (250ml)',
    defaultServingGrams: 250,
  },
  {
    id: 'drink_kopi_americano_black',
    name: 'Kopi Hitam / Americano Dingin / Panas (Tanpa Gula)',
    indonesianName: 'Kopi Hitam Polos Americano',
    category: 'Dairy & Drinks',
    calories: 2,
    protein: 0.2,
    carbs: 0.3,
    fat: 0.0,
    defaultServingText: '1 Cup (240ml)',
    defaultServingGrams: 240,
  },

  // --- MIE INSTAN & FAST FOOD POPULER ---
  {
    id: 'food_indomie_goreng_original',
    name: 'Indomie Mi Goreng Spesial Original',
    indonesianName: 'Indomie Goreng Original',
    category: 'Staples',
    calories: 458,
    protein: 9.4,
    carbs: 63.5,
    fat: 18.8,
    fiber: 3.5,
    defaultServingText: '1 Bungkus Kering (85g)',
    defaultServingGrams: 85,
  },
  {
    id: 'food_indomie_kuah_kari_ayam',
    name: 'Indomie Kuah Rasa Kari Ayam',
    indonesianName: 'Indomie Kari Ayam Kuah',
    category: 'Staples',
    calories: 420,
    protein: 9.0,
    carbs: 58.0,
    fat: 17.0,
    defaultServingText: '1 Bungkus Kering (72g)',
    defaultServingGrams: 72,
  },
  {
    id: 'food_indomie_kuah_soto_mie',
    name: 'Indomie Kuah Rasa Soto Mie',
    indonesianName: 'Indomie Soto Mie Kuah',
    category: 'Staples',
    calories: 415,
    protein: 8.5,
    carbs: 59.0,
    fat: 16.5,
    defaultServingText: '1 Bungkus Kering (70g)',
    defaultServingGrams: 70,
  },
  {
    id: 'food_sedaap_goreng',
    name: 'Mie Sedaap Goreng Kriuk',
    indonesianName: 'Mie Sedaap Goreng',
    category: 'Staples',
    calories: 470,
    protein: 10.0,
    carbs: 64.0,
    fat: 19.5,
    defaultServingText: '1 Bungkus Kering (90g)',
    defaultServingGrams: 90,
  },
  {
    id: 'food_kfc_ayam_crispy_dada',
    name: 'Ayam Goreng KFC Crispy (Dada)',
    indonesianName: 'KFC Fried Chicken Dada Crispy',
    category: 'Proteins',
    calories: 270,
    protein: 24.0,
    carbs: 11.0,
    fat: 15.0,
    defaultServingText: '1 Potong Dada (130g)',
    defaultServingGrams: 130,
  },
  {
    id: 'food_kfc_ayam_crispy_paha',
    name: 'Ayam Goreng KFC Crispy (Paha Atas)',
    indonesianName: 'KFC Fried Chicken Paha Crispy',
    category: 'Proteins',
    calories: 290,
    protein: 18.0,
    carbs: 11.0,
    fat: 19.0,
    defaultServingText: '1 Potong Paha (110g)',
    defaultServingGrams: 110,
  },
  {
    id: 'food_mcd_french_fries',
    name: 'Kentang Goreng McDonald / McD French Fries',
    indonesianName: 'McD French Fries Kentang Goreng',
    category: 'Snacks',
    calories: 320,
    protein: 3.8,
    carbs: 41.0,
    fat: 16.0,
    fiber: 3.5,
    defaultServingText: '1 Porsi Medium (115g)',
    defaultServingGrams: 115,
  },
  {
    id: 'food_mcd_burger_cheeseburger',
    name: 'McDonald Cheeseburger Burger Daging Keju',
    indonesianName: 'McD Cheeseburger',
    category: 'Snacks',
    calories: 260,
    protein: 13.0,
    carbs: 26.0,
    fat: 11.5,
    defaultServingText: '1 Burger (115g)',
    defaultServingGrams: 115,
  },

  // --- SEREAL, MUESLI & GRANOLA ---
  {
    id: 'food_syifa_muesli_choco_milk',
    name: 'Syifa Muesli Choco Milk',
    indonesianName: 'Syifa Muesli Choco Milk Coklat',
    category: 'Staples',
    calories: 395,
    protein: 11.2,
    carbs: 68.5,
    fat: 7.8,
    fiber: 8.5,
    defaultServingText: '1 Porsi (40g / ~4 sdm)',
    defaultServingGrams: 40,
  },
  {
    id: 'food_syifa_muesli_original_fruit',
    name: 'Syifa Muesli Fruit & Nuts Original',
    indonesianName: 'Syifa Muesli Original Buah Kacang',
    category: 'Staples',
    calories: 380,
    protein: 10.5,
    carbs: 69.0,
    fat: 6.8,
    fiber: 9.0,
    defaultServingText: '1 Porsi (40g / ~4 sdm)',
    defaultServingGrams: 40,
  },
  {
    id: 'food_koko_krunch',
    name: 'Nestle Koko Krunch Cereal',
    indonesianName: 'Koko Krunch Sereal Coklat',
    category: 'Staples',
    calories: 387,
    protein: 7.3,
    carbs: 78.5,
    fat: 3.5,
    fiber: 6.0,
    defaultServingText: '1 Mangkok (30g)',
    defaultServingGrams: 30,
  },
  {
    id: 'food_milo_cereal',
    name: 'Nestle Milo Cereal',
    indonesianName: 'Milo Cereal Sereal',
    category: 'Staples',
    calories: 390,
    protein: 8.0,
    carbs: 76.0,
    fat: 4.8,
    fiber: 5.5,
    defaultServingText: '1 Mangkok (30g)',
    defaultServingGrams: 30,
  },
  {
    id: 'food_kelloggs_corn_flakes',
    name: 'Kelloggs Corn Flakes Jagung',
    indonesianName: 'Kelloggs Corn Flakes',
    category: 'Staples',
    calories: 378,
    protein: 7.5,
    carbs: 84.0,
    fat: 0.9,
    fiber: 3.0,
    defaultServingText: '1 Mangkok (30g)',
    defaultServingGrams: 30,
  },
  {
    id: 'food_kelloggs_froot_loops',
    name: 'Kelloggs Froot Loops',
    indonesianName: 'Froot Loops Sereal Buah',
    category: 'Staples',
    calories: 395,
    protein: 5.0,
    carbs: 86.0,
    fat: 3.0,
    fiber: 2.5,
    defaultServingText: '1 Mangkok (30g)',
    defaultServingGrams: 30,
  },
  {
    id: 'food_quaker_rolled_oats',
    name: 'Quaker Rolled Oats (Merah)',
    indonesianName: 'Quaker Oats Merah Rolled Oat',
    category: 'Staples',
    calories: 375,
    protein: 12.5,
    carbs: 65.0,
    fat: 7.0,
    fiber: 10.0,
    defaultServingText: '4 Sendok Makan (35g)',
    defaultServingGrams: 35,
  },
  {
    id: 'food_quaker_instant_oatmeal',
    name: 'Quaker Instant Oatmeal (Biru)',
    indonesianName: 'Quaker Oats Biru Instan',
    category: 'Staples',
    calories: 367,
    protein: 11.5,
    carbs: 66.0,
    fat: 6.5,
    fiber: 9.5,
    defaultServingText: '4 Sendok Makan (35g)',
    defaultServingGrams: 35,
  },
  {
    id: 'food_east_bali_cashews_granola',
    name: 'YAVA / East Bali Cashews Granola Chocolate Vanilla',
    indonesianName: 'YAVA Granola Coklat Vanilla',
    category: 'Staples',
    calories: 450,
    protein: 9.0,
    carbs: 64.0,
    fat: 18.0,
    fiber: 7.0,
    defaultServingText: '1 Porsi (35g)',
    defaultServingGrams: 35,
  },
  {
    id: 'food_granola_creations_cinnamon',
    name: 'Granola Creations Cinnamon & Raisin',
    indonesianName: 'Granola Creations Kayu Manis Kismis',
    category: 'Staples',
    calories: 440,
    protein: 8.5,
    carbs: 66.0,
    fat: 16.0,
    fiber: 6.5,
    defaultServingText: '1 Porsi (40g)',
    defaultServingGrams: 40,
  },

  // --- SUSU UHT REGULAR / FULL CREAM (ULTRA, GREENFIELDS, DIAMOND, DLL) ---
  {
    id: 'food_ultra_milk_full_cream',
    name: 'Ultra Milk UHT Full Cream Putih',
    indonesianName: 'Susu Ultra Milk Full Cream',
    category: 'Dairy & Drinks',
    calories: 60,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.2,
    defaultServingText: '1 Kotak / Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_ultra_milk_cokelat',
    name: 'Ultra Milk UHT Cokelat (Chocolate)',
    indonesianName: 'Susu Ultra Milk Rasa Cokelat',
    category: 'Dairy & Drinks',
    calories: 80,
    protein: 3.0,
    carbs: 12.0,
    fat: 2.2,
    defaultServingText: '1 Kotak / Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_ultra_milk_stroberi',
    name: 'Ultra Milk UHT Rasa Stroberi',
    indonesianName: 'Susu Ultra Milk Stroberi',
    category: 'Dairy & Drinks',
    calories: 75,
    protein: 2.8,
    carbs: 11.5,
    fat: 2.0,
    defaultServingText: '1 Kotak / Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_greenfields_uht_full_cream',
    name: 'Greenfields UHT Fresh Milk / Full Cream',
    indonesianName: 'Susu Greenfields UHT Full Cream',
    category: 'Dairy & Drinks',
    calories: 63,
    protein: 3.3,
    carbs: 4.5,
    fat: 3.5,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_greenfields_uht_choco',
    name: 'Greenfields UHT Choco Malt / Cokelat',
    indonesianName: 'Susu Greenfields Cokelat',
    category: 'Dairy & Drinks',
    calories: 85,
    protein: 3.4,
    carbs: 12.5,
    fat: 2.5,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_diamond_uht_full_cream',
    name: 'Diamond Milk UHT Full Cream',
    indonesianName: 'Susu Diamond UHT Full Cream',
    category: 'Dairy & Drinks',
    calories: 62,
    protein: 3.1,
    carbs: 4.9,
    fat: 3.3,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_diamond_uht_cokelat',
    name: 'Diamond Milk UHT Cokelat',
    indonesianName: 'Susu Diamond UHT Coklat',
    category: 'Dairy & Drinks',
    calories: 82,
    protein: 3.0,
    carbs: 12.5,
    fat: 2.4,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_frisian_flag_uht_purefarm_full_cream',
    name: 'Frisian Flag UHT Purefarm Full Cream',
    indonesianName: 'Susu Frisian Flag Purefarm Full Cream',
    category: 'Dairy & Drinks',
    calories: 65,
    protein: 3.2,
    carbs: 5.0,
    fat: 3.5,
    defaultServingText: '1 Kotak / Gelas (225ml)',
    defaultServingGrams: 225,
  },
  {
    id: 'food_indomilk_uht_full_cream',
    name: 'Indomilk UHT Plain Full Cream',
    indonesianName: 'Susu Indomilk UHT Plain',
    category: 'Dairy & Drinks',
    calories: 62,
    protein: 3.1,
    carbs: 4.7,
    fat: 3.4,
    defaultServingText: '1 Kotak / Gelas (190ml)',
    defaultServingGrams: 190,
  },
  {
    id: 'food_bear_brand_nestle',
    name: 'Bear Brand Susu Steril Nestle (Susu Beruang)',
    indonesianName: 'Susu Bear Brand Steril',
    category: 'Dairy & Drinks',
    calories: 63,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.7,
    defaultServingText: '1 Kaleng (189ml)',
    defaultServingGrams: 189,
  },
  {
    id: 'food_cimory_uht_full_cream',
    name: 'Cimory UHT Fresh Milk Full Cream',
    indonesianName: 'Susu Cimory UHT Full Cream',
    category: 'Dairy & Drinks',
    calories: 65,
    protein: 3.2,
    carbs: 5.2,
    fat: 3.5,
    defaultServingText: '1 Kotak (250ml)',
    defaultServingGrams: 250,
  },
  {
    id: 'food_hometown_fresh_milk',
    name: 'Hometown Dairy Fresh Milk Pasteurisasi',
    indonesianName: 'Susu Hometown Fresh Milk',
    category: 'Dairy & Drinks',
    calories: 67,
    protein: 3.4,
    carbs: 4.8,
    fat: 3.8,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },

  // --- SUSU LOW FAT / SKIM / BEBAS LEMAK BERBAGAI MERK ---
  {
    id: 'food_ultra_milk_low_fat_hi_calcium',
    name: 'Ultra Milk Low Fat Hi-Cal Tinggi Kalsium',
    indonesianName: 'Susu Ultra Milk Low Fat',
    category: 'Dairy & Drinks',
    calories: 43,
    protein: 3.5,
    carbs: 5.2,
    fat: 1.0,
    defaultServingText: '1 Kotak / Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_ultra_milk_low_fat_choco',
    name: 'Ultra Milk Low Fat Choco Cokelat',
    indonesianName: 'Susu Ultra Milk Low Fat Cokelat',
    category: 'Dairy & Drinks',
    calories: 65,
    protein: 3.5,
    carbs: 11.0,
    fat: 1.0,
    defaultServingText: '1 Kotak / Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_greenfields_uht_low_fat',
    name: 'Greenfields UHT Low Fat Milk (1.1% Fat)',
    indonesianName: 'Susu Greenfields Low Fat UHT',
    category: 'Dairy & Drinks',
    calories: 44,
    protein: 3.4,
    carbs: 5.0,
    fat: 1.1,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_greenfields_skim_milk',
    name: 'Greenfields Skim Milk Bebas Lemak (0.1% Fat)',
    indonesianName: 'Susu Greenfields Skim Milk',
    category: 'Dairy & Drinks',
    calories: 35,
    protein: 3.5,
    carbs: 5.1,
    fat: 0.1,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_diamond_uht_low_fat',
    name: 'Diamond Milk UHT Low Fat Rendah Lemak',
    indonesianName: 'Susu Diamond Low Fat',
    category: 'Dairy & Drinks',
    calories: 45,
    protein: 3.3,
    carbs: 5.1,
    fat: 1.2,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_frisian_flag_low_fat',
    name: 'Frisian Flag Purefarm Low Fat French Vanilla / Plain',
    indonesianName: 'Susu Frisian Flag Low Fat',
    category: 'Dairy & Drinks',
    calories: 45,
    protein: 3.2,
    carbs: 6.0,
    fat: 1.1,
    defaultServingText: '1 Gelas (225ml)',
    defaultServingGrams: 225,
  },
  {
    id: 'food_tropicana_slim_low_fat_vanilla',
    name: 'Tropicana Slim Low Fat Milk Vanilla Bebas Gula',
    indonesianName: 'Susu Tropicana Slim Low Fat Vanilla',
    category: 'Dairy & Drinks',
    calories: 40,
    protein: 3.5,
    carbs: 5.0,
    fat: 0.8,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_hilo_active_chocolate',
    name: 'HiLo Active Susu Tinggi Kalsium Rendah Lemak Coklat',
    indonesianName: 'Susu HiLo Active Cokelat Rendah Lemak',
    category: 'Dairy & Drinks',
    calories: 70,
    protein: 4.2,
    carbs: 11.0,
    fat: 1.2,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_hilo_teen_vanilla',
    name: 'HiLo Teen Susu Tinggi Kalsium Rendah Lemak Vanilla',
    indonesianName: 'Susu HiLo Teen Vanilla',
    category: 'Dairy & Drinks',
    calories: 68,
    protein: 4.0,
    carbs: 11.5,
    fat: 1.0,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_oatside_barista_blend',
    name: 'Oatside Oat Milk Barista Blend',
    indonesianName: 'Susu Gandum Oatside Barista Blend',
    category: 'Dairy & Drinks',
    calories: 65,
    protein: 1.0,
    carbs: 8.5,
    fat: 3.0,
    defaultServingText: '1 Gelas (200ml)',
    defaultServingGrams: 200,
  },
  {
    id: 'food_vsoy_multigrain',
    name: 'V-Soy Multi-Grain Soya Milk Susu Kedelai',
    indonesianName: 'Susu Kedelai V-Soy Multigrain',
    category: 'Dairy & Drinks',
    calories: 68,
    protein: 3.5,
    carbs: 8.0,
    fat: 2.4,
    defaultServingText: '1 Botol (300ml)',
    defaultServingGrams: 300,
  },
];

/**
 * Filter items from builtin database + custom foods by search query
 */
export function searchFoodItems(
  query: string,
  customItems: FoodItem[] = []
): FoodItem[] {
  const combined = [...customItems, ...BUILTIN_FOOD_DATABASE];
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) return combined;

  const tokens = trimmed.split(/\s+/);
  return combined.filter((item) => {
    const haystack = [
      item.name.toLowerCase(),
      item.indonesianName?.toLowerCase() || '',
      item.category.toLowerCase(),
    ].join(' ');

    return tokens.every((token) => haystack.includes(token));
  });
}

/**
 * Compute nutrition values for a given weight in grams
 */
export function calculateNutrientsForWeight(item: FoodItem, grams: number) {
  const factor = Math.max(0, grams) / 100;
  return {
    calories: Math.round(item.calories * factor),
    protein: Math.round(item.protein * factor * 10) / 10,
    carbs: Math.round(item.carbs * factor * 10) / 10,
    fat: Math.round(item.fat * factor * 10) / 10,
    fiber: item.fiber !== undefined ? Math.round(item.fiber * factor * 10) / 10 : undefined,
  };
}
