import { StyleSheet } from 'react-native';
import { COLORS, RADIUS } from '../constants/theme';

// Shared cash/expense accents (mirrors types/finance TX_TYPE_THEME)
const INCOME = '#10B981';
const EXPENSE = '#F43F5E';

export const financeStyles = StyleSheet.create({
  // ------------------------------------------------------------------
  // Screen shell + header
  // ------------------------------------------------------------------
  container: {
    flex: 1,
    backgroundColor: COLORS.bgCanvas,
    paddingHorizontal: 22,
    paddingTop: 0,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.7,
  },
  slogan: {
    fontSize: 13,
    color: COLORS.textMuted,
    marginTop: 4,
    fontWeight: '500',
    letterSpacing: -0.1,
  },
  headerRightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  headerAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.finance,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: RADIUS.md,
    gap: 6,
    minHeight: 42,
  },
  headerAddBtnText: {
    color: '#06131F',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.2,
  },

  // ------------------------------------------------------------------
  // Hero net worth card
  // ------------------------------------------------------------------
  heroCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xxl,
    padding: 24,
    marginBottom: 22,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 5,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  balanceLabel: {
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  currencyToggle: {
    flexDirection: 'row',
    backgroundColor: COLORS.bgCardSub,
    borderRadius: RADIUS.md,
    padding: 4,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexShrink: 0,
  },
  toggleBtn: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: RADIUS.sm,
  },
  toggleBtnActive: {
    backgroundColor: COLORS.finance,
  },
  toggleBtnText: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  toggleBtnTextActive: {
    color: '#06131F',
    fontWeight: '800',
  },
  balanceAmount: {
    fontSize: 32,
    fontWeight: '900',
    color: COLORS.textPrimary,
    letterSpacing: -0.8,
    fontVariant: ['tabular-nums'],
    marginBottom: 14,
  },
  heroSubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  heroSubBadge: {
    backgroundColor: 'rgba(56, 189, 248, 0.14)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.32)',
  },
  heroSubBadgeText: {
    fontSize: 11.5,
    color: COLORS.finance,
    fontWeight: '700',
  },

  // ------------------------------------------------------------------
  // Month navigator
  // ------------------------------------------------------------------
  monthNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xl,
    padding: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  monthNavBtn: {
    width: 42,
    height: 42,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.bgCardSub,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    flexShrink: 0,
  },
  monthCenterTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    minWidth: 0,
  },
  monthNavText: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textPrimary,
    flexShrink: 1,
  },
  currentMonthBadge: {
    backgroundColor: 'rgba(56, 189, 248, 0.16)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    flexShrink: 0,
  },
  currentMonthBadgeText: {
    color: COLORS.finance,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.5,
  },

  // ------------------------------------------------------------------
  // Cash flow bento
  // ------------------------------------------------------------------
  cashflowSection: {
    marginBottom: 28,
    gap: 14,
  },
  cashflowRow: {
    flexDirection: 'row',
    gap: 14,
  },
  cashflowCard: {
    flex: 1,
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xl,
    padding: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cashflowCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  cashflowIconWrap: {
    width: 28,
    height: 28,
    borderRadius: RADIUS.sm,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  cashflowLabel: {
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  cashflowValue: {
    fontSize: 16,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  netFlowCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xl,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  netFlowLeft: {
    flex: 1,
    minWidth: 0,
  },
  netFlowLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textMuted,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  netFlowValue: {
    fontSize: 18,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  netFlowBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    flexShrink: 0,
  },
  netFlowBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },

  // ------------------------------------------------------------------
  // Section headers
  // ------------------------------------------------------------------
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
    gap: 10,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.textSecondary,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    flexShrink: 1,
  },
  countBadge: {
    backgroundColor: 'rgba(56, 189, 248, 0.14)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.3)',
    flexShrink: 0,
  },
  countBadgeText: {
    color: COLORS.finance,
    fontSize: 11,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  seeAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(56, 189, 248, 0.12)',
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.3)',
    flexShrink: 0,
  },
  seeAllText: {
    color: COLORS.finance,
    fontSize: 12,
    fontWeight: '700',
  },
  headerHistoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bgCardSub,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 5,
    flexShrink: 0,
  },
  headerHistoryBtnText: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },

  // ------------------------------------------------------------------
  // View-mode switcher
  // ------------------------------------------------------------------
  viewSwitchRow: {
    flexDirection: 'row',
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.lg,
    padding: 5,
    marginTop: 6,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 5,
  },
  viewSwitchItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: RADIUS.md,
  },
  viewSwitchItemActive: {
    backgroundColor: COLORS.finance,
  },
  viewSwitchText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textMuted,
    flexShrink: 1,
  },
  viewSwitchTextActive: {
    color: '#06131F',
    fontWeight: '800',
  },

  // ------------------------------------------------------------------
  // Quick filter tabs
  // ------------------------------------------------------------------
  filterTabRow: {
    flexDirection: 'row',
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.lg,
    padding: 5,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 5,
  },
  filterTabItem: {
    flex: 1,
    paddingVertical: 11,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: RADIUS.md,
  },
  filterTabItemActive: {
    backgroundColor: COLORS.bgCardSub,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  filterTabItemText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: COLORS.textMuted,
  },
  filterTabItemTextActive: {
    color: COLORS.textPrimary,
    fontWeight: '800',
  },

  // ------------------------------------------------------------------
  // Empty state
  // ------------------------------------------------------------------
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
    paddingHorizontal: 28,
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xxl,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.28)',
    borderStyle: 'dashed',
    marginBottom: 24,
  },
  emptyIconBox: {
    width: 62,
    height: 62,
    borderRadius: RADIUS.lg,
    backgroundColor: 'rgba(56, 189, 248, 0.14)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.3)',
  },
  emptyText: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptySubText: {
    color: COLORS.textMuted,
    fontSize: 12.5,
    marginTop: 8,
    textAlign: 'center',
    lineHeight: 19,
  },
  emptyActionBtn: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: COLORS.finance,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.finance,
    minHeight: 44,
  },
  emptyActionBtnText: {
    color: '#06131F',
    fontSize: 13,
    fontWeight: '800',
  },

  // ------------------------------------------------------------------
  // Transaction card
  // ------------------------------------------------------------------
  txCard: {
    backgroundColor: COLORS.bgCard,
    padding: 14,
    borderRadius: RADIUS.xl,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  txMainBlock: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconContainer: {
    width: 42,
    height: 42,
    borderRadius: 13,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    flexShrink: 0,
  },
  txBody: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    gap: 6,
  },
  txMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  txDesc: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.2,
  },
  txAmount: {
    fontSize: 14.5,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
    letterSpacing: -0.4,
    textAlign: 'right',
    flexShrink: 0,
    maxWidth: '48%',
  },
  textIncome: {
    color: INCOME,
  },
  textExpense: {
    color: EXPENSE,
  },
  txMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  txCategoryBadgeWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  txCategoryBadge: {
    backgroundColor: COLORS.bgCardSub,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  txCategoryBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.textSecondary,
  },
  txDateText: {
    fontSize: 10.5,
    color: COLORS.textMuted,
    fontWeight: '600',
    flexShrink: 0,
  },
  txBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    gap: 8,
  },
  txAccountPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.bgCardSub,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  txAccountPillText: {
    fontSize: 10.5,
    fontWeight: '600',
    color: COLORS.textSecondary,
    flexShrink: 1,
    minWidth: 0,
  },
  txActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  txActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.bgCardSub,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  txActionBtnDelete: {
    borderColor: 'rgba(244, 63, 94, 0.32)',
    backgroundColor: 'rgba(244, 63, 94, 0.1)',
  },
  txActionBtnText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: COLORS.textMuted,
  },

  // ------------------------------------------------------------------
  // Account card
  // ------------------------------------------------------------------
  accCard: {
    backgroundColor: '#11141D',
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.border,
    position: 'relative',
    overflow: 'hidden',
  },
  accTopBar: {
    height: 4,
    width: '100%',
  },
  accCardBody: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
  },
  accHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 18,
    gap: 12,
  },
  accHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  accIconBox: {
    width: 46,
    height: 46,
    borderRadius: RADIUS.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
    borderWidth: 1,
    flexShrink: 0,
  },
  accTitleGroup: {
    flex: 1,
    minWidth: 0,
  },
  accName: {
    fontSize: 16.5,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.2,
    marginBottom: 6,
  },
  accMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  accTypeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.full,
    flexShrink: 0,
  },
  accTypeBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  accDescText: {
    fontSize: 11.5,
    color: COLORS.textMuted,
    flexShrink: 1,
  },
  accHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  accCurrencyPill: {
    backgroundColor: 'rgba(56, 189, 248, 0.13)',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.3)',
  },
  accCurrencyPillUSD: {
    backgroundColor: 'rgba(192, 132, 252, 0.16)',
    borderColor: 'rgba(192, 132, 252, 0.36)',
  },
  accCurrencyPillText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: COLORS.finance,
  },
  accChevronBox: {
    width: 30,
    height: 30,
    borderRadius: RADIUS.full,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  accBalanceRow: {
    marginBottom: 16,
  },
  accBalanceLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.9,
    marginBottom: 6,
  },
  accBalanceAmount: {
    fontSize: 24,
    fontWeight: '900',
    color: COLORS.textPrimary,
    letterSpacing: -0.5,
    fontVariant: ['tabular-nums'],
  },
  accBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 14,
    gap: 10,
  },
  accPocketBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.bgCardSub,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexShrink: 0,
  },
  accPocketBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textMuted,
  },
  accPocketsScroll: {
    gap: 8,
    flexGrow: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  accPocketMiniTag: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  accPocketMiniTagText: {
    fontSize: 10.5,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  accPocketMiniTagMore: {
    backgroundColor: COLORS.bgCardSub,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
  },
  accPocketMiniTagMoreText: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.textMuted,
  },

  // ------------------------------------------------------------------
  // Add account dashed card
  // ------------------------------------------------------------------
  addAccountDashedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(56, 189, 248, 0.05)',
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: 'rgba(56, 189, 248, 0.32)',
    borderRadius: RADIUS.xl,
    paddingVertical: 16,
    paddingHorizontal: 18,
    gap: 14,
    marginTop: 2,
  },
  addAccIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(56, 189, 248, 0.16)',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  addAccTitle: {
    color: COLORS.finance,
    fontSize: 14,
    fontWeight: '800',
  },
  addAccSubtitle: {
    color: COLORS.textMuted,
    fontSize: 11.5,
    fontWeight: '500',
    marginTop: 3,
  },
});
