import { StyleSheet, Platform, StatusBar } from 'react-native';

export const financeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#09090B',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  header: {
    marginBottom: 20,
    marginTop: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FAFAFA',
    letterSpacing: -0.5,
  },
  slogan: {
    fontSize: 13,
    color: '#A1A1AA',
    marginTop: 4,
    fontWeight: '500',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FAFAFA',
    letterSpacing: 0.2,
  },
  addAccBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#38BDF8',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 4,
  },
  addAccText: {
    color: '#09090B',
    fontSize: 12,
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    color: '#71717A',
    fontSize: 14,
    marginTop: 12,
    fontWeight: '500',
  },
  fab: {
    position: 'absolute',
    bottom: 32,
    right: 24,
    backgroundColor: '#38BDF8',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#38BDF8',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
  },

  // Hero Card
  heroCard: {
    backgroundColor: '#18181B',
    borderRadius: 24,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  balanceLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#71717A',
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  balanceAmount: {
    fontSize: 32,
    fontWeight: '900',
    color: '#FAFAFA',
    letterSpacing: -0.5,
  },
  balanceAmountUSD: {
    fontSize: 15,
    fontWeight: '600',
    color: '#38BDF8',
    marginTop: 2,
  },
  heroDivider: {
    height: 1,
    backgroundColor: '#27272A',
    marginVertical: 18,
  },
  monthSelectorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  monthNavBtn: {
    padding: 6,
    borderRadius: 10,
    backgroundColor: '#09090B',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  monthSelectorText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FAFAFA',
  },
  summaryContainer: {
    gap: 10,
  },
  summaryTwoCol: {
    flexDirection: 'row',
    gap: 10,
  },
  summaryBox: {
    flex: 1,
    backgroundColor: '#09090B',
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  summaryLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#A1A1AA',
  },
  summaryIncome: {
    fontSize: 15,
    fontWeight: '800',
    color: '#4ADE80',
  },
  summaryIncomeSub: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4ADE80',
    marginTop: 2,
  },
  summaryExpense: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FF453A',
  },
  summaryExpenseSub: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FF453A',
    marginTop: 2,
  },
  balanceBoxFull: {
    backgroundColor: '#09090B',
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  balanceValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  summaryIncomeLarge: {
    fontSize: 18,
    fontWeight: '800',
    color: '#4ADE80',
  },
  summaryExpenseLarge: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FF453A',
  },

  // Account Card
  accCard: {
    backgroundColor: '#18181B',
    width: 220,
    padding: 18,
    borderRadius: 20,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#27272A',
    position: 'relative',
    overflow: 'hidden',
  },
  accCardAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
  },
  accHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  accName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FAFAFA',
  },
  accTotalBalance: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FAFAFA',
    marginBottom: 14,
  },
  subAccPreview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  subAccPreviewText: {
    fontSize: 12,
    color: '#71717A',
    fontWeight: '500',
  },

  // Transaction Card
  txCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#18181B',
    padding: 14,
    borderRadius: 18,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  iconIncome: {
    backgroundColor: 'rgba(74, 222, 128, 0.12)',
  },
  iconExpense: {
    backgroundColor: 'rgba(255, 69, 58, 0.12)',
  },
  txInfo: {
    flex: 1,
    marginRight: 10,
  },
  txDesc: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FAFAFA',
    marginBottom: 3,
  },
  txSub: {
    fontSize: 11,
    color: '#71717A',
    fontWeight: '500',
  },
  txRight: {
    alignItems: 'flex-end',
  },
  txAmount: {
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 4,
  },
  textIncome: {
    color: '#4ADE80',
  },
  textExpense: {
    color: '#FF453A',
  },
  txActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionBtn: {
    padding: 4,
  },

  // Modal Common
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'flex-end',
  },
  modalOverlayCenter: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalOverlayDismissArea: {
    flex: 1,
  },
  modalContent: {
    backgroundColor: '#18181B',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  modalContentSmall: {
    backgroundColor: '#18181B',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#3F3F46',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 22,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FAFAFA',
  },
  modalTitleCenter: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FAFAFA',
    textAlign: 'center',
    marginBottom: 16,
  },
  modalSubtitle: {
    fontSize: 12,
    color: '#A1A1AA',
    marginTop: 4,
  },
  typeRow: {
    flexDirection: 'row',
    backgroundColor: '#09090B',
    borderRadius: 16,
    padding: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  typeRowSmall: {
    flexDirection: 'row',
    backgroundColor: '#09090B',
    borderRadius: 12,
    padding: 3,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  typeBtn: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 12,
  },
  typeBtnSmall: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 10,
  },
  typeBtnExpense: {
    backgroundColor: '#FF453A',
  },
  typeBtnIncome: {
    backgroundColor: '#4ADE80',
  },
  typeBtnSmallActive: {
    backgroundColor: '#38BDF8',
  },
  typeBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#71717A',
  },
  typeBtnTextSmall: {
    fontSize: 12,
    fontWeight: '700',
    color: '#71717A',
  },
  typeBtnTextActive: {
    color: '#09090B',
  },
  typeBtnTextSmallActive: {
    color: '#09090B',
  },
  amountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    paddingVertical: 8,
  },
  currencySymbol: {
    fontSize: 28,
    fontWeight: '800',
    color: '#38BDF8',
    marginRight: 8,
  },
  inputAmountLarge: {
    fontSize: 36,
    fontWeight: '900',
    color: '#FAFAFA',
    minWidth: 100,
    textAlign: 'left',
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#71717A',
    letterSpacing: 1,
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#09090B',
    color: '#FAFAFA',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#27272A',
    marginBottom: 16,
  },
  dialogInput: {
    backgroundColor: '#09090B',
    color: '#FAFAFA',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#27272A',
    marginVertical: 16,
  },
  dialogInputLeft: {
    backgroundColor: '#09090B',
    color: '#FAFAFA',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#27272A',
    marginBottom: 20,
  },
  datePickerContainer: {
    marginBottom: 16,
  },
  datePickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#09090B',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  datePickerText: {
    color: '#FAFAFA',
    fontSize: 14,
    fontWeight: '600',
  },
  chipScroll: {
    flexDirection: 'row',
    flexGrow: 0,
    marginBottom: 16,
    marginHorizontal: -24,
    paddingHorizontal: 24,
  },
  chipScrollSmall: {
    flexDirection: 'row',
    flexGrow: 0,
    marginBottom: 14,
    marginHorizontal: -24,
    paddingHorizontal: 24,
  },
  chip: {
    backgroundColor: '#09090B',
    borderWidth: 1,
    borderColor: '#27272A',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    marginRight: 8,
  },
  chipActive: {
    backgroundColor: '#38BDF8',
    borderColor: '#38BDF8',
  },
  chipText: {
    color: '#A1A1AA',
    fontSize: 13,
    fontWeight: '600',
  },
  chipTextActive: {
    color: '#09090B',
    fontWeight: '800',
  },
  chipSub: {
    backgroundColor: '#09090B',
    borderWidth: 1,
    borderColor: '#27272A',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    marginRight: 6,
    marginBottom: 12,
  },
  chipSubActive: {
    backgroundColor: '#0284C7',
    borderColor: '#0284C7',
  },
  chipSubText: {
    color: '#71717A',
    fontSize: 12,
    fontWeight: '500',
  },
  chipSubTextActive: {
    color: '#FAFAFA',
    fontWeight: '700',
  },
  chipAdd: {
    borderWidth: 1,
    borderColor: '#38BDF8',
    borderStyle: 'dashed',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chipAddText: {
    color: '#38BDF8',
    fontSize: 13,
    fontWeight: '700',
  },
  saveButton: {
    backgroundColor: '#38BDF8',
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: 'center',
    marginTop: 8,
  },
  saveButtonText: {
    color: '#09090B',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  dialogActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  dialogBtnCancel: {
    flex: 1,
    backgroundColor: '#27272A',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
  },
  dialogBtnCancelText: {
    color: '#FAFAFA',
    fontSize: 13,
    fontWeight: '700',
  },
  dialogBtnConfirm: {
    flex: 1,
    backgroundColor: '#38BDF8',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
  },
  dialogBtnConfirmText: {
    color: '#09090B',
    fontSize: 13,
    fontWeight: '800',
  },

  // Sub Account in Detail Modal
  subAccDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#09090B',
    padding: 14,
    borderRadius: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  subAccDetailName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FAFAFA',
  },
  subAccDetailBalance: {
    fontSize: 14,
    fontWeight: '700',
    color: '#38BDF8',
  },

  // Calendar in Finance Modal
  calendarHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  calendarNavBtn: {
    padding: 6,
  },
  calendarMonthText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FAFAFA',
  },
  calendarDaysHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 10,
  },
  calendarDayName: {
    color: '#71717A',
    fontSize: 11,
    fontWeight: '700',
    width: 32,
    textAlign: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginBottom: 20,
  },
  calendarCell: {
    width: '14.28%',
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 19,
  },
  calendarCellSelected: {
    backgroundColor: '#38BDF8',
  },
  calendarCellToday: {
    borderWidth: 1,
    borderColor: '#38BDF8',
  },
  calendarDayText: {
    color: '#FAFAFA',
    fontSize: 13,
    fontWeight: '500',
  },
  calendarDayTextSelected: {
    color: '#09090B',
    fontWeight: '800',
  },
  calendarDayTextToday: {
    color: '#38BDF8',
  },
});