import { StyleSheet, Platform, StatusBar } from 'react-native';

export const fitnessStyles = StyleSheet.create({
  // Main Screen
  container: {
    flex: 1,
    backgroundColor: '#09090B',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  header: {
    marginBottom: 20,
    marginTop: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FAFAFA',
    letterSpacing: -0.5,
  },
  slogan: {
    fontSize: 13,
    color: '#A1A1AA',
    marginTop: 4,
    fontWeight: '500',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 48,
    paddingHorizontal: 24,
  },
  emptyIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#18181B',
    borderWidth: 1,
    borderColor: '#27272A',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  emptyText: {
    color: '#FAFAFA',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptySubText: {
    color: '#71717A',
    fontSize: 13,
    marginTop: 6,
    textAlign: 'center',
    lineHeight: 18,
  },
  fab: {
    position: 'absolute',
    bottom: 32,
    right: 24,
    backgroundColor: '#FF6B00',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#FF6B00',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
  },

  // Redesigned Modern DateStrip
  dateStripContainer: {
    marginBottom: 20,
    backgroundColor: '#18181B',
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  monthHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
    paddingHorizontal: 4,
  },
  monthLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  monthLabelText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FAFAFA',
    letterSpacing: 0.2,
  },
  todayBadge: {
    backgroundColor: 'rgba(255, 107, 0, 0.12)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 0, 0.3)',
  },
  todayBadgeText: {
    fontSize: 11,
    color: '#FF6B00',
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  dateStripRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dayCard: {
    flex: 1,
    height: 64,
    backgroundColor: '#09090B',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 3,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  dayCardActive: {
    backgroundColor: '#FF6B00',
    borderColor: '#FF6B00',
  },
  dayCardToday: {
    borderColor: '#FF6B00',
  },
  dayTextShort: {
    fontSize: 11,
    color: '#71717A',
    fontWeight: '700',
    marginBottom: 2,
    textTransform: 'uppercase',
  },
  dayTextShortActive: {
    color: '#09090B',
    fontWeight: '800',
  },
  dayTextNumber: {
    fontSize: 16,
    color: '#FAFAFA',
    fontWeight: '800',
  },
  dayTextNumberActive: {
    color: '#09090B',
  },
  futureDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#FF6B00',
    marginTop: 2,
  },

  // HeroMetrics
  heroCard: {
    backgroundColor: '#18181B',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  heroTitle: {
    fontSize: 13,
    color: '#A1A1AA',
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  heroDateBadge: {
    fontSize: 12,
    color: '#FF6B00',
    fontWeight: '700',
  },
  volumeRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 16,
  },
  volumeText: {
    fontSize: 34,
    fontWeight: '900',
    color: '#FAFAFA',
    letterSpacing: -0.5,
  },
  volumeUnit: {
    fontSize: 16,
    color: '#FF6B00',
    fontWeight: '700',
    marginLeft: 6,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  statBox: {
    flex: 1,
    backgroundColor: '#09090B',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  statLabel: {
    fontSize: 11,
    color: '#71717A',
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  statValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FAFAFA',
  },

  // CategoryFilter
  filterContainer: {
    marginBottom: 20,
    marginHorizontal: -20,
  },
  filterScroll: {
    paddingHorizontal: 20,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#18181B',
    borderWidth: 1,
    borderColor: '#27272A',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: '#FF6B00',
    borderColor: '#FF6B00',
  },
  filterIcon: {
    marginRight: 6,
  },
  filterText: {
    color: '#A1A1AA',
    fontSize: 13,
    fontWeight: '600',
  },
  filterTextActive: {
    color: '#09090B',
    fontWeight: '800',
  },

  // WorkoutCard
  workoutCard: {
    backgroundColor: '#18181B',
    padding: 18,
    borderRadius: 22,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  workoutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  workoutIconContainer: {
    backgroundColor: 'rgba(255, 107, 0, 0.12)',
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  workoutTitleContainer: {
    flex: 1,
  },
  workoutExercise: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FAFAFA',
    marginBottom: 3,
  },
  workoutCategory: {
    fontSize: 12,
    color: '#A1A1AA',
    fontWeight: '500',
  },
  workoutDeleteButton: {
    padding: 6,
  },
  workoutDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#09090B',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  workoutPill: {
    color: '#FAFAFA',
    fontSize: 14,
    fontWeight: '700',
  },
  workoutUnit: {
    fontSize: 12,
    color: '#71717A',
    fontWeight: '500',
  },
  workoutDot: {
    color: '#3F3F46',
    marginHorizontal: 10,
    fontSize: 14,
  },
  workoutHighlight: {
    color: '#FF6B00',
  },

  // Modal Common Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'flex-end',
  },
  modalOverlayCenter: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalDismissArea: {
    flex: 1,
  },
  modalContent: {
    backgroundColor: '#18181B',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#3F3F46',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 22,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FAFAFA',
  },
  modalSubtitle: {
    fontSize: 12,
    color: '#A1A1AA',
    marginTop: 4,
  },
  formLabel: {
    color: '#A1A1AA',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
    letterSpacing: 1,
  },
  formInput: {
    backgroundColor: '#09090B',
    color: '#FAFAFA',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    marginBottom: 20,
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  formNumberInput: {
    backgroundColor: '#09090B',
    color: '#FAFAFA',
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 16,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  categorySelectionScroll: {
    flexDirection: 'row',
    flexGrow: 0,
    marginBottom: 20,
    marginHorizontal: -24,
    paddingHorizontal: 24,
  },
  categorySelectionChip: {
    backgroundColor: '#09090B',
    borderWidth: 1,
    borderColor: '#27272A',
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 18,
    marginRight: 8,
  },
  categorySelectionChipActive: {
    backgroundColor: '#FF6B00',
    borderColor: '#FF6B00',
  },
  categorySelectionText: {
    color: '#A1A1AA',
    fontSize: 13,
    fontWeight: '600',
  },
  categorySelectionTextActive: {
    color: '#09090B',
    fontWeight: '800',
  },
  suggestionSelectionScroll: {
    flexDirection: 'row',
    flexGrow: 0,
    marginBottom: 22,
    marginHorizontal: -24,
    paddingHorizontal: 24,
  },
  suggestionSelectionChip: {
    backgroundColor: '#27272A',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    marginRight: 8,
  },
  suggestionSelectionText: {
    color: '#FAFAFA',
    fontSize: 13,
    fontWeight: '500',
  },
  rowNumberInputs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
    gap: 10,
  },
  inputGroupCol: {
    flex: 1,
  },
  primaryActionButton: {
    backgroundColor: '#FF6B00',
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: 'center',
  },
  primaryActionButtonText: {
    color: '#09090B',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.5,
  },

  // Calendar Modal
  calendarBox: {
    backgroundColor: '#18181B',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  calendarMonthText: {
    color: '#FAFAFA',
    fontSize: 16,
    fontWeight: '800',
  },
  calendarDaysHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 8,
  },
  calendarDayName: {
    color: '#71717A',
    fontSize: 11,
    fontWeight: '700',
    width: 34,
    textAlign: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginBottom: 20,
  },
  calendarCell: {
    width: '14.28%',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  calendarCellSelected: {
    backgroundColor: '#FF6B00',
  },
  calendarCellToday: {
    borderWidth: 1,
    borderColor: '#FF6B00',
  },
  calendarDayText: {
    color: '#FAFAFA',
    fontSize: 14,
    fontWeight: '500',
  },
  calendarDayTextSelected: {
    color: '#09090B',
    fontWeight: '800',
  },
  calendarDayTextToday: {
    color: '#FF6B00',
  },
  secondaryButton: {
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: '#27272A',
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#FAFAFA',
    fontSize: 14,
    fontWeight: '700',
  },

  // Warning Modal
  warningBox: {
    backgroundColor: '#18181B',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    width: '100%',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  warningIconContainer: {
    backgroundColor: 'rgba(255, 107, 0, 0.15)',
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  warningTitle: {
    color: '#FAFAFA',
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 8,
  },
  warningMessage: {
    color: '#A1A1AA',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
});