import { StyleSheet, Platform, StatusBar } from 'react-native';

export const habitStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#09090B',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 20,
  },
  headerTitleBold: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FAFAFA',
    letterSpacing: -0.5,
  },
  headerSubtitleLight: {
    fontSize: 13,
    color: '#71717A',
    marginTop: 2,
    fontWeight: '500',
  },
  headerAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#8E97FD',
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 12,
    gap: 4,
  },
  headerAddBtnText: {
    color: '#09090B',
    fontSize: 12,
    fontWeight: '800',
  },
  todayBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#121215',
    borderWidth: 1,
    borderColor: '#27272A',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 14,
  },
  todayBannerText: {
    color: '#8E97FD',
    fontSize: 11,
    fontWeight: '700',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  sectionTitle: {
    color: '#71717A',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  sectionHint: {
    color: '#3F3F46',
    fontSize: 11,
    fontWeight: '500',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    color: '#FAFAFA',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 12,
  },
  emptySubText: {
    color: '#71717A',
    fontSize: 12,
    marginTop: 4,
  },

  // 2-Column Grid Wrapper
  habitGridWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },

  // Date Navigator
  dateNavContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#18181B',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  dateNavBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#27272A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateNavTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateNavDisplayText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FAFAFA',
  },

  // Category Filter
  filterContainer: {
    marginBottom: 14,
    marginHorizontal: -20,
  },
  filterScroll: {
    paddingHorizontal: 20,
  },
  filterChip: {
    backgroundColor: '#18181B',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  filterChipActive: {
    backgroundColor: '#8E97FD',
    borderColor: '#8E97FD',
  },
  filterChipText: {
    color: '#71717A',
    fontSize: 12,
    fontWeight: '700',
  },
  filterChipTextActive: {
    color: '#09090B',
    fontWeight: '800',
  },

  // Progress Card
  progressCard: {
    backgroundColor: '#18181B',
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  progressTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FAFAFA',
  },
  progressBadge: {
    backgroundColor: '#09090B',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  progressBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#8E97FD',
  },
  progressBarBackground: {
    height: 6,
    backgroundColor: '#27272A',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#8E97FD',
    borderRadius: 3,
  },

  // Modal Umum
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'flex-end',
  },
  modalOverlayCenter: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalOverlayDismissArea: {
    flex: 1,
  },
  modalContent: {
    backgroundColor: '#18181B',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 12,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  modalContentSmall: {
    backgroundColor: '#18181B',
    borderRadius: 24,
    padding: 22,
    width: '100%',
    borderWidth: 1,
    borderColor: '#27272A',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#3F3F46',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#27272A',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FAFAFA',
  },
  modalSubtitle: {
    fontSize: 12,
    color: '#71717A',
    marginTop: 2,
  },
  modalTitleCenter: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FAFAFA',
    textAlign: 'center',
    marginBottom: 4,
  },
  modalSubtitleCenter: {
    fontSize: 12,
    color: '#71717A',
    textAlign: 'center',
    marginBottom: 18,
    lineHeight: 16,
  },

  // Form Input Modal
  inputLabel: {
    color: '#71717A',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginBottom: 10,
  },
  input: {
    backgroundColor: '#18181B',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#FAFAFA',
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#27272A',
    fontWeight: '600',
  },
  inputCenter: {
    backgroundColor: '#09090B',
    color: '#FAFAFA',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 14,
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#27272A',
    marginBottom: 18,
    fontWeight: '600',
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  chipScroll: {
    flexDirection: 'row',
    flexGrow: 0,
    marginBottom: 16,
  },
  chipModal: {
    backgroundColor: '#18181B',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#27272A',
    marginRight: 8,
  },
  chipModalActive: {
    backgroundColor: '#8E97FD',
    borderColor: '#8E97FD',
  },
  chipModalText: {
    color: '#71717A',
    fontSize: 12,
    fontWeight: '600',
  },
  chipModalTextActive: {
    color: '#09090B',
    fontWeight: '800',
  },
  chipAdd: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(142, 151, 253, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(142, 151, 253, 0.3)',
    borderStyle: 'dashed',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  chipAddText: {
    color: '#8E97FD',
    fontSize: 12,
    fontWeight: '700',
  },
  saveButton: {
    backgroundColor: '#8E97FD',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 28,
  },
  saveButtonText: {
    color: '#09090B',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.5,
  },

  // Modal Actions
  dialogActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  dialogBtnCancel: {
    flex: 1,
    backgroundColor: '#27272A',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  dialogBtnCancelText: {
    color: '#FAFAFA',
    fontSize: 12,
    fontWeight: '700',
  },
  dialogBtnConfirm: {
    flex: 1,
    backgroundColor: '#8E97FD',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  dialogBtnConfirmText: {
    color: '#09090B',
    fontSize: 12,
    fontWeight: '800',
  },
  btnNeutral: {
    backgroundColor: '#8E97FD',
  },
  textNeutral: {
    color: '#09090B',
  },
  btnDestructive: {
    backgroundColor: '#FF453A',
  },
  textDestructive: {
    color: '#FAFAFA',
  },
});