import { StyleSheet, Platform } from 'react-native';
import { COLORS, RADIUS } from '../constants/theme';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgCanvas,
    paddingHorizontal: 22,
    paddingTop: 0,
  },
  scrollContent: {
    paddingTop: 4,
  },

  // ------------------------------------------------------------------
  // Header
  // ------------------------------------------------------------------
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 24,
  },
  userProfile: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.bgCardSub,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 3,
  },
  avatarText: {
    color: COLORS.accentHover,
    fontSize: 18,
    fontWeight: '800',
  },
  greetingSubtext: {
    color: COLORS.textMuted,
    fontSize: 12.5,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  bulletDot: {
    color: COLORS.textMuted,
    fontSize: 12,
  },
  userNameHeading: {
    color: COLORS.textPrimary,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.4,
    marginTop: 2,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dateText: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  settingsBtn: {
    width: 42,
    height: 42,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.bgCardSub,
    borderWidth: 1,
    borderColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },

  // ------------------------------------------------------------------
  // Hero "Today" card
  // ------------------------------------------------------------------
  heroCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xxl,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 20,
    overflow: 'hidden',
    marginBottom: 34,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.42,
    shadowRadius: 22,
    elevation: 5,
  },
  heroBody: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ringColumn: {
    alignItems: 'center',
    marginRight: 18,
  },
  ringWrap: {
    width: 108,
    height: 108,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ringLabel: {
    color: COLORS.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 10,
    textAlign: 'center',
  },
  ringCenter: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ringPercent: {
    color: COLORS.textPrimary,
    fontSize: 25,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  ringCaption: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  heroStats: {
    flex: 1,
    gap: 9,
  },
  heroStat: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 14,
    gap: 10,
  },
  heroStatIcon: {
    width: 36,
    height: 36,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  heroStatTextWrap: {
    flex: 1,
  },
  heroStatValue: {
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  heroStatValueMuted: {
    color: COLORS.textMuted,
    fontSize: 11.5,
    fontWeight: '600',
  },
  heroStatLabel: {
    color: COLORS.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },

  // ------------------------------------------------------------------
  // Section headers
  // ------------------------------------------------------------------
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionTitleText: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  sectionActionText: {
    color: COLORS.accentHover,
    fontSize: 12.5,
    fontWeight: '700',
  },

  // ------------------------------------------------------------------
  // Today's Activities
  // ------------------------------------------------------------------
  habitsPreviewCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xxl,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 18,
    paddingVertical: 8,
    marginBottom: 34,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 4,
  },
  habitItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    minHeight: 58,
  },
  habitIconChip: {
    width: 38,
    height: 38,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    marginRight: 12,
  },
  habitItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  habitItemTitle: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 4,
  },
  habitItemTitleDone: {
    color: COLORS.textMuted,
    textDecorationLine: 'line-through',
  },
  habitItemMeta: {
    color: COLORS.textMuted,
    fontSize: 12.5,
    fontWeight: '500',
  },
  priorityBadge: {
    backgroundColor: 'rgba(244, 63, 94, 0.15)',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: 'rgba(244, 63, 94, 0.3)',
  },
  priorityBadgeText: {
    color: COLORS.danger,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  emptyCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xxl,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 34,
  },
  emptyCardIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(56, 189, 248, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.25)',
  },
  emptyCardTitle: {
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 5,
    textAlign: 'center',
  },
  emptyCardSub: {
    color: COLORS.textMuted,
    fontSize: 12.5,
    textAlign: 'center',
    lineHeight: 18,
  },

  // ------------------------------------------------------------------
  // Modal Styles (used by HomeSettingsModal)
  // ------------------------------------------------------------------
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: 'flex-end',
  },
  dismissArea: {
    flex: 1,
  },
  modalContent: {
    backgroundColor: COLORS.bgCard,
    borderTopLeftRadius: RADIUS.modal,
    borderTopRightRadius: RADIUS.modal,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 38 : 28,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  modalHandle: {
    width: 36,
    height: 4,
    backgroundColor: COLORS.borderLight,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 12,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.3,
  },
  settingsGroup: {
    marginBottom: 24,
  },
  inputGroupLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  profileInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileInput: {
    flex: 1,
    backgroundColor: COLORS.bgCardSub,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
  },
  saveNameBtn: {
    backgroundColor: COLORS.accent,
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: RADIUS.md,
  },
  saveNameBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bgCardSub,
    padding: 14,
    borderRadius: RADIUS.lg,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  menuIconBox: {
    backgroundColor: COLORS.bgCard,
    width: 38,
    height: 38,
    borderRadius: RADIUS.sm,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  menuTextContainer: {
    flex: 1,
  },
  menuItemTitle: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 2,
  },
  menuItemDesc: {
    color: COLORS.textMuted,
    fontSize: 12,
  },
  resetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.dangerSoft,
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: 'rgba(244, 63, 94, 0.3)',
    gap: 8,
  },
  resetButtonText: {
    color: COLORS.danger,
    fontSize: 13,
    fontWeight: '700',
  },
  resetWarning: {
    color: COLORS.textMuted,
    fontSize: 12,
    marginTop: 8,
    lineHeight: 18,
    textAlign: 'center',
  },
});
