import { StyleSheet, Platform, StatusBar } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#09090B',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  userProfile: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: '#18181B',
    borderWidth: 1,
    borderColor: '#27272A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  avatarText: {
    color: '#D4FF00',
    fontSize: 18,
    fontWeight: '800',
  },
  greetingText: {
    color: '#FAFAFA',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  dateText: {
    color: '#71717A',
    fontSize: 13,
    fontWeight: '500',
    marginTop: 2,
    letterSpacing: 0.2,
  },
  settingsBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#18181B',
    borderWidth: 1,
    borderColor: '#27272A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionLabel: {
    color: '#71717A',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginBottom: 12,
  },
  bentoContainer: {
    marginBottom: 24,
    gap: 12,
  },
  bentoCardLarge: {
    backgroundColor: '#18181B',
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badgeIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeTextMuted: {
    color: '#A1A1AA',
    fontSize: 12,
    fontWeight: '600',
  },
  bentoBody: {
    marginVertical: 14,
  },
  metricLarge: {
    color: '#FAFAFA',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: -1,
  },
  metricSub: {
    color: '#A1A1AA',
    fontSize: 13,
    marginTop: 4,
    fontWeight: '500',
  },
  progressBarBg: {
    height: 6,
    backgroundColor: '#27272A',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#8E97FD',
    borderRadius: 3,
  },
  bentoRow: {
    flexDirection: 'row',
    gap: 12,
  },
  bentoCardHalf: {
    flex: 1,
    backgroundColor: '#18181B',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#27272A',
    justifyContent: 'space-between',
    minHeight: 155,
  },
  bentoTitle: {
    color: '#FAFAFA',
    fontSize: 17,
    fontWeight: '700',
    marginTop: 12,
  },
  bentoSubtitle: {
    color: '#71717A',
    fontSize: 12,
    marginTop: 2,
    marginBottom: 14,
    lineHeight: 16,
  },
  statusPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#1E2412',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusPillText: {
    color: '#D4FF00',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  quickActionRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#18181B',
    paddingVertical: 15,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#27272A',
    gap: 8,
  },
  actionBtnText: {
    color: '#FAFAFA',
    fontSize: 13,
    fontWeight: '700',
  },
  focusContainer: {
    backgroundColor: '#18181B',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#27272A',
    borderLeftWidth: 4,
    borderLeftColor: '#FF453A',
  },
  focusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  focusHeaderText: {
    color: '#FF453A',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  focusBodyText: {
    color: '#A1A1AA',
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '400',
  },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'flex-end',
  },
  dismissArea: {
    flex: 1,
  },
  modalContent: {
    backgroundColor: '#18181B',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#3F3F46',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FAFAFA',
  },
  settingsGroup: {
    marginBottom: 24,
  },
  inputGroupLabel: {
    color: '#71717A',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 10,
  },
  profileInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileInput: {
    flex: 1,
    backgroundColor: '#09090B',
    color: '#FAFAFA',
    borderWidth: 1,
    borderColor: '#27272A',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
  },
  saveNameBtn: {
    backgroundColor: '#D4FF00',
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: 14,
  },
  saveNameBtnText: {
    color: '#09090B',
    fontSize: 12,
    fontWeight: '800',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#09090B',
    padding: 14,
    borderRadius: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#27272A',
  },
  menuIconBox: {
    backgroundColor: '#18181B',
    width: 38,
    height: 38,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  menuTextContainer: {
    flex: 1,
  },
  menuItemTitle: {
    color: '#FAFAFA',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 2,
  },
  menuItemDesc: {
    color: '#71717A',
    fontSize: 12,
  },
  resetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 69, 58, 0.1)',
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 69, 58, 0.3)',
  },
  resetButtonText: {
    color: '#FF453A',
    fontSize: 13,
    fontWeight: '700',
  },
  resetWarning: {
    color: '#71717A',
    fontSize: 12,
    marginTop: 8,
    lineHeight: 18,
    textAlign: 'center',
  },
});