import { StyleSheet, Platform } from 'react-native';
import { COLORS, RADIUS } from '../constants/theme';

export const nutritionStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgCanvas,
    paddingHorizontal: 22,
    paddingTop: 0,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.6,
  },
  slogan: {
    fontSize: 13,
    color: COLORS.textMuted,
    marginTop: 3,
    fontWeight: '500',
    letterSpacing: -0.1,
  },
  headerRightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  targetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bgCardSub,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 5,
  },
  targetBtnText: {
    color: COLORS.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  headerAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.nutrition,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: RADIUS.md,
    gap: 4,
  },
  headerAddBtnText: {
    color: '#08090C',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.2,
  },

  // Date Navigation Bar
  dateNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.lg,
    padding: 6,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  dateNavBtn: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.bgCardSub,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  dateCenterTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  dateNavText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  todayBadge: {
    backgroundColor: COLORS.nutritionLight,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: 'rgba(45, 212, 191, 0.25)',
  },
  todayBadgeText: {
    color: COLORS.nutrition,
    fontSize: 10,
    fontWeight: '800',
  },

  // Hero Macro Summary Card
  heroCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xl,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  calorieMainCol: {
    flex: 1,
  },
  calorieLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 1.1,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  calorieBigRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
  },
  calorieNumber: {
    fontSize: 34,
    fontWeight: '900',
    color: COLORS.textPrimary,
    letterSpacing: -1,
    fontVariant: ['tabular-nums'],
  },
  calorieTargetSub: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textMuted,
    fontVariant: ['tabular-nums'],
  },
  calorieRemainingBox: {
    backgroundColor: COLORS.bgCardSub,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'flex-end',
  },
  remainingLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  remainingNumber: {
    fontSize: 15,
    fontWeight: '800',
    color: COLORS.nutrition,
    fontVariant: ['tabular-nums'],
  },

  // Calorie Progress Bar
  calorieBarTrack: {
    height: 7,
    backgroundColor: COLORS.bgCardSub,
    borderRadius: RADIUS.full,
    overflow: 'hidden',
    marginBottom: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  calorieBarFill: {
    height: '100%',
    backgroundColor: COLORS.nutrition,
    borderRadius: RADIUS.full,
  },

  // Macro Row (Protein, Carbs, Fat)
  macroRow: {
    flexDirection: 'row',
    gap: 8,
  },
  macroCol: {
    flex: 1,
    backgroundColor: COLORS.bgCardSub,
    borderRadius: RADIUS.md,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  macroHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  macroName: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  macroAmountText: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.textPrimary,
    fontVariant: ['tabular-nums'],
    marginBottom: 6,
  },
  macroTargetText: {
    fontSize: 10,
    fontWeight: '500',
    color: COLORS.textMuted,
  },
  macroBarTrack: {
    height: 4,
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.full,
    overflow: 'hidden',
  },
  macroBarFill: {
    height: '100%',
    borderRadius: RADIUS.full,
  },

  // Meal Section (Breakfast, Lunch, Dinner, Snack)
  mealSectionCard: {
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.xl,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  mealHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  mealTitleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  mealIconWrap: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.bgCardSub,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  mealLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  mealCaloriesBadge: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.textMuted,
    fontVariant: ['tabular-nums'],
    marginTop: 1,
  },
  mealAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.nutritionLight,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: 'rgba(45, 212, 191, 0.25)',
    gap: 4,
  },
  mealAddBtnText: {
    color: COLORS.nutrition,
    fontSize: 11,
    fontWeight: '800',
  },

  // Meal Bottom Add Button
  mealBottomAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    marginTop: 6,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'rgba(45, 212, 191, 0.28)',
    borderRadius: RADIUS.md,
    backgroundColor: 'rgba(45, 212, 191, 0.05)',
    gap: 6,
  },
  mealBottomAddBtnText: {
    color: COLORS.nutrition,
    fontSize: 12,
    fontWeight: '700',
  },

  // Empty Meal Text
  mealEmptyRow: {
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
  },
  mealEmptyText: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: '500',
  },

  // Log Item Card
  logItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bgCardSub,
    padding: 12,
    borderRadius: RADIUS.md,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  logInfo: {
    flex: 1,
    marginRight: 8,
  },
  logFoodName: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: 2,
  },
  logServingSub: {
    fontSize: 11,
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  logRightCol: {
    alignItems: 'flex-end',
    marginRight: 10,
  },
  logCaloriesVal: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.textPrimary,
    fontVariant: ['tabular-nums'],
  },
  logMacroSummary: {
    fontSize: 10,
    color: COLORS.textMuted,
    fontVariant: ['tabular-nums'],
    marginTop: 2,
  },
  logActionBtn: {
    padding: 6,
    borderRadius: RADIUS.sm,
  },

  // Food Search Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: 'flex-end',
  },
  dismissArea: {
    flex: 1,
  },
  modalContent: {
    backgroundColor: COLORS.bgCard,
    borderTopLeftRadius: RADIUS.modal,
    borderTopRightRadius: RADIUS.modal,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 38 : 28,
    maxHeight: '85%',
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  modalHandle: {
    width: 36,
    height: 4,
    backgroundColor: COLORS.borderLight,
    borderRadius: RADIUS.full,
    alignSelf: 'center',
    marginBottom: 12,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.3,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bgCardSub,
    borderRadius: RADIUS.md,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'ios' ? 10 : 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    color: COLORS.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },

  // Category Filter Chips
  categoryChipScroll: {
    flexDirection: 'row',
    flexGrow: 0,
    marginBottom: 14,
  },
  categoryChip: {
    backgroundColor: COLORS.bgCardSub,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginRight: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryChipActive: {
    backgroundColor: COLORS.nutritionLight,
    borderColor: COLORS.nutrition,
  },
  categoryChipText: {
    color: COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  categoryChipTextActive: {
    color: COLORS.nutrition,
    fontWeight: '800',
  },

  // Food Item Selection Row
  foodSearchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.bgCardSub,
    padding: 14,
    borderRadius: RADIUS.md,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  foodSearchRowActive: {
    borderColor: COLORS.nutrition,
    backgroundColor: COLORS.nutritionLight,
  },
  foodSearchTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: 2,
  },
  foodSearchServing: {
    fontSize: 11,
    color: COLORS.textMuted,
  },
  foodSearchCals: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.nutrition,
    fontVariant: ['tabular-nums'],
  },
  foodSearchMacros: {
    fontSize: 10,
    color: COLORS.textMuted,
    fontVariant: ['tabular-nums'],
    marginTop: 2,
  },

  // Serving Portion Adjuster Modal / Card
  adjusterCard: {
    backgroundColor: COLORS.bgCardSub,
    borderRadius: RADIUS.lg,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  adjusterTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  adjusterLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  modalContentPortion: {
    maxHeight: '92%',
    paddingBottom: Platform.OS === 'ios' ? 32 : 24,
  },
  portionAdjusterCard: {
    backgroundColor: COLORS.bgCardSub,
    borderRadius: RADIUS.lg,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  portionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  doneKeyboardBtn: {
    backgroundColor: COLORS.nutritionLight,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: 'rgba(45, 212, 191, 0.3)',
  },
  doneKeyboardBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.nutrition,
  },
  gramControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  stepperBtn: {
    width: 48,
    height: 48,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.bgCard,
    borderWidth: 1,
    borderColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gramInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderColor: COLORS.nutrition,
    height: 48,
    paddingHorizontal: 12,
  },
  gramInputLarge: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.textPrimary,
    textAlign: 'center',
    minWidth: 55,
    padding: 0,
    fontVariant: ['tabular-nums'],
  },
  gramUnitSuffix: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginLeft: 4,
  },
  quickServingGrid: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
  },
  quickServingPill: {
    flex: 1,
    backgroundColor: COLORS.bgCard,
    paddingVertical: 9,
    paddingHorizontal: 4,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickServingPillActive: {
    backgroundColor: COLORS.nutritionLight,
    borderColor: COLORS.nutrition,
  },
  quickServingPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textMuted,
  },
  quickServingPillTextActive: {
    color: COLORS.nutrition,
    fontWeight: '800',
  },
  nutritionPreviewSection: {
    backgroundColor: COLORS.bgCardSub,
    borderRadius: RADIUS.lg,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  calorieBannerBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.bgCard,
    borderRadius: RADIUS.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.borderSubtle,
  },
  calorieBannerValue: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.nutrition,
    fontVariant: ['tabular-nums'],
  },
  calorieBannerUnit: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textMuted,
    marginTop: 4,
  },
  calorieBannerSub: {
    fontSize: 11,
    color: COLORS.textMuted,
    fontWeight: '500',
  },
  macroColumnsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  macroPillBox: {
    flex: 1,
    backgroundColor: COLORS.bgCard,
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    borderWidth: 1,
  },
  macroPillVal: {
    fontSize: 14,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
    marginBottom: 2,
  },
  macroPillName: {
    fontSize: 10,
    fontWeight: '700',
    color: COLORS.textMuted,
    textTransform: 'uppercase',
  },
  // Save / Log Button
  logSaveBtn: {
    backgroundColor: COLORS.nutrition,
    flexDirection: 'row',
    paddingVertical: 15,
    borderRadius: RADIUS.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    marginBottom: 8,
  },
  logSaveBtnText: {
    color: '#08090C',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.3,
  },

  // Custom Food Form
  formGroup: {
    marginBottom: 14,
  },
  formLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.textMuted,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  formInput: {
    backgroundColor: COLORS.bgCardSub,
    color: COLORS.textPrimary,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: RADIUS.md,
    fontSize: 13,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  formRow: {
    flexDirection: 'row',
    gap: 8,
  },
});
